### ISSUE TITLE
sky spot status json error when the shell prints additional warning

### ISSUE THREAD

**Issue by lhqing** [skypilot-org/skypilot#1181]
Hi Sky team,

One of my labmate's bash env has some setting problem that his bash continues prints warning like this: 
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

This then triggers a sky issue when checking `sky spot status`

```
$ sky spot status -r -a 
Fetching managed spot job statuses...
Traceback (most recent call last):
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/utils/common_utils.py", line 157, in _record
    return f(*args, **kwargs)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/cli.py", line 911, in invoke
    return super().invoke(ctx)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/utils/common_utils.py", line 157, in _record
    return f(*args, **kwargs)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/cli.py", line 911, in invoke
    return super().invoke(ctx)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/utils/common_utils.py", line 178, in _record
    return f(*args, **kwargs)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/cli.py", line 2573, in spot_status
    job_table = core.spot_status(refresh=refresh)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/core.py", line 495, in spot_status
    jobs = spot.load_spot_job_queue(job_table_json)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/site-packages/sky/spot/spot_utils.py", line 318, in load_spot_job_queue
    jobs = json.loads(json_str)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/gale/netapp/home/zhoujt/miniconda3/envs/sky/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This error is because the bash warning is included in the `job_table_json` content inside the `sky.core.spot_status` function
https://github.com/skypilot-org/skypilot/blob/master/sky/core.py#L494-L495

This is the content of `job_table_json` that caused this error:
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[
  {
    "job_id": 4,
    "job_name": "test4",
    "resources": "1x [CPU:0.5]",
    "submitted_at": 1664514525.2864213,
    "status": "STARTING",
    "run_timestamp": "sky-2022-09-30-05-08-45-286360",
    "start_at": null,
    "end_at": null,
    "last_recovered_at": -1.0,
    "recovery_count": 0,
    "job_duration": 0,
    "cluster_resources": "1x GCP(n2d-standard-4[Spot])",
    "region": "us-west1"
  },
  ... # normal json content
]

```

**Comment by Michaelvll** [comment]
Thank you for identifying and digging into this issue! We just submitted a PR #1182 to solve it. Please give it a try by running `git pull; git checkout spot-table-decode` and run `sky spot launch ''` to update the spot controller, when you get a chance. : )
