### ISSUE TITLE
Sky spot launch filemount failure on RISE on-prem

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1266]
Looks like one smoke test is not passing on our on-prem server with NFS for home directory.
This bug can be triggered when `/tmp` is mounted on a different disk than the files in `filemount`. @Michaelvll do you think directly copy the files rather than linking them under `/tmp` would fix this?
```
(sky) weichiang@blaze:~/repos/skypilot$ sky spot launch examples/managed_spot_with_storage.yaml
Task from YAML spec: examples/managed_spot_with_storage.yam
Launching a new spot task 'sky-1f59-weichiang'. Proceed? [Y/n]: Y
I 10-17 20:23:10 execution.py:497] Translating file_mounts with local source paths to SkyPilot Storage...
I 10-17 20:23:10 execution.py:523] Workdir './examples' will be synced to cloud storage 'skypilot-workdir-weichiang-4d1ee39f'.
I 10-17 20:23:10 execution.py:547] Folder in local file mount '~/tmp-workdir' will be synced to SkyPilot storage skypilot-filemounts-folder-weichiang-4d1ee39f-0.
Traceback (most recent call last):
  File "/data/weichiang/miniconda3/envs/sky/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 179, in _record
    return f(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 918, in invoke
    return super().invoke(ctx)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 179, in _record
    return f(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 918, in invoke
    return super().invoke(ctx)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 200, in _record
    return f(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 200, in _record
    return f(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 2617, in spot_launch
    sky.spot_launch(dag,
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 200, in _record
    return f(*args, **kwargs)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/execution.py", line 432, in spot_launch
    task = _maybe_translate_local_file_mounts_and_sync_up(task)
  File "/data/weichiang/miniconda3/envs/sky/lib/python3.8/site-packages/sky/execution.py", line 563, in _maybe_translate_local_file_mounts_and_sync_up
    os.link(os.path.abspath(os.path.expanduser(src)),
OSError: [Errno 18] Invalid cross-device link: '/home/eecs/weichiang/tmpfile' -> '/tmp/skypilot-filemounts-files-4d1ee39f/file-0'
```

**Comment by Michaelvll** [comment]
Since we currently do not support uploading multiple files to a SkyPilot Storage, we have to hard link the files into a single folder and upload the folder to the bucket. It works fine when the files are on the same devices, but the error here shows that it will fail for having multiple devices.

A temporary solution is to copy the files when the hardlink fails. However, a better solution is to support a list of source file for SkyPilot Storage as mentioned in #1070 and #1226. @romilbhardwaj has proposed an API that should solve the problem [here](https://github.com/skypilot-org/skypilot/issues/1226#issuecomment-1275280248):
```
/dst:
    name: bucket-name
    source_list: [/path/to/file1, /path/to/file2]
```
