### ISSUE TITLE
Azure `sky logs` CredentialUnavailableError

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1273]
Tested this on most recent master.

When syncing logs from any job ran on an Azure-provisioned VM, there is a timeout error from unable to get authentication token for Azure. 

```
Traceback (most recent call last):
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 149, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/anaconda/envs/py38_default/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/anaconda/envs/py38_default/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/anaconda/envs/py38_default/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/anaconda/envs/py38_default/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/anaconda/envs/py38_default/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource https://management.azure.com']' timed out after 10 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 483, in run
    self._initialize_autoscaler()
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 230, in _initialize_autoscaler
    self.autoscaler = StandardAutoscaler(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 216, in __init__
    self.reset(errors_fatal=True)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 977, in reset
    raise e
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 921, in reset
    self.provider = _get_node_provider(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/ray/autoscaler/_private/providers.py", line 242, in _get_node_provider
    new_provider = provider_cls(provider_config, cluster_name)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/sky/skylet/providers/azure/node_provider.py", line 65, in __init__
    _configure_resource_group({"provider": provider_config})
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/sky/skylet/providers/azure/config.py", line 69, in _configure_resource_group
    resource_client.resource_groups.create_or_update(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 154, in create_or_update
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 116, in send
    self.on_request(request)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 81, in get_token
    output = _run_command(command)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 170, in _run_command
    six.raise_from(error, ex)
  File "<string>", line 3, in raise_from
azure.identity._exceptions.CredentialUnavailableError: Failed to invoke the Azure CLI
```

**Comment by Michaelvll** [comment]
I have seen these errors before sometimes during the smoke tests. Can we have a reproducible snippet for it?

**Comment by michaelzhiluo** [comment]
@Michaelvll  `sky launch -c hello --cloud azure [ANYTHING]` ; applies for all Azure clusters

**Comment by Michaelvll** [comment]
I can confirm that the following commands will reproduce the problem
```
sky launch -c test-azure --cloud azure
sky exec test-azure 'echo hi'
```

The logs of the task will be shown correctly, but before the logs is shown, there is the error shown above.

**Comment by Michaelvll** [comment]
This is output by the ray autoscaler, who failed to access the credential file on the remote VM. The problem is tracked in the Azure-cli issue https://github.com/Azure/azure-cli/issues/20404.

It should not affect the single node behavior, as we will not access any other resources that need the crediential, but when it comes to multiple nodes. A workaround for this is to patch the Azure-cli file by increase the timeout as mentioned in the https://github.com/Azure/azure-cli/issues/20404#issuecomment-1249575110
