### ISSUE TITLE
Mounted storage failed when downloading tensorflow dataset

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1281]
I wanted to use mounted storage with an S3 bucket to hold data from `tensorflow-dataset` for my spot jobs. But I met some `Too many open files` error during `tfds.load('cifar10')`.
I'm not sure whether it's a goofys limitation or some incorrect configurations?
```
(sky-cdef-weichiang pid=12719) Downloading and preparing dataset 162.17 MiB (download: 162.17 MiB, generated: 132.40 MiB, total: 294.58 MiB) to /tensorflow-datasets/cifar10/3.0.2...
Extraction completed...:   0%|          | 0/1 [00:19<?, ? file/s]0/1 [00:03<?, ? url/s]
Dl Size...: 100%|██████████| 162/162 [00:19<00:00,  8.34 MiB/s]162 [00:02<00:20,  7.21 MiB/s]
Dl Completed...: 100%|██████████| 1/1 [00:19<00:00, 19.42s/ url]       | 0/1 [00:09<?, ? file/s]
(sky-cdef-weichiang pid=12719) Traceback (most recent call last):
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/sky_workdir/train.py", line 143, in <module>
(sky-cdef-weichiang pid=12719)     main()
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/sky_workdir/train.py", line 24, in main
(sky-cdef-weichiang pid=12719)     train_loader = load_dataset(config, train=True)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/sky_workdir/train.py", line 95, in load_dataset
(sky-cdef-weichiang pid=12719)     dataset = tfds.load('cifar10', split=split)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/tensorflow_datasets/core/logging/__init__.py", line 250, in decorator
(sky-cdef-weichiang pid=12719)     return function(*args, **kwargs)
....
(sky-cdef-weichiang pid=12719)     structure[0], [func(*x) for x in entries],
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/tensorflow_datasets/core/download/download_manager.py", line 770, in <lambda>
(sky-cdef-weichiang pid=12719)     res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/promise/promise.py", line 512, in get
(sky-cdef-weichiang pid=12719)     return self._target_settled_value(_raise=True)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/promise/promise.py", line 516, in _target_settled_value
(sky-cdef-weichiang pid=12719)     return self._target()._settled_value(_raise)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/promise/promise.py", line 226, in _settled_value
(sky-cdef-weichiang pid=12719)     reraise(type(raise_val), raise_val, self._traceback)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/six.py", line 719, in reraise
(sky-cdef-weichiang pid=12719)     raise value
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/promise/promise.py", line 844, in handle_future_result
(sky-cdef-weichiang pid=12719)     resolve(future.result())
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
(sky-cdef-weichiang pid=12719)     return self.__get_result()
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
(sky-cdef-weichiang pid=12719)     raise self._exception
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
(sky-cdef-weichiang pid=12719)     result = self.fn(*self.args, **self.kwargs)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/tensorflow_datasets/core/download/extractor.py", line 114, in _sync_extract
(sky-cdef-weichiang pid=12719)     tf.io.gfile.rename(to_path_tmp, to_path)
(sky-cdef-weichiang pid=12719)   File "/home/gcpuser/miniconda3/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 620, in rename_v2
(sky-cdef-weichiang pid=12719)     _pywrap_file_io.RenameFile(
(sky-cdef-weichiang pid=12719) tensorflow.python.framework.errors_impl.ResourceExhaustedError: /tensorflow-datasets/downloads/extracted/TAR_GZ.cs.toronto.edu_kriz_cifar-10-binaryxKOMUKG8Xzo
cVTfyFVq51o-fJese2Nnd2j2ymlm8od0.tar.gz.incomplete_ffc0ef89e2754b14a9ea35fd4adae532; Too many open files
```

**Comment by concretevitamin** [comment]
Is this part of running a managed spot TPU job?  cc @romilbhardwaj

**Comment by infwinston** [comment]
> Is this part of running a managed spot TPU job? cc @romilbhardwaj

Yes, I'd like the data to be downloaded only once for future Spot VMs to re-use. However I met this issue during data download.

**Comment by romilbhardwaj** [comment]
thanks for sharing the logs @infwinston! can you also share the yaml so I can reproduce this?

**Comment by infwinston** [comment]
Yes I prepare a minimal example to reproduce it. Hope it helps!
COPY mode should work but it will require an additional step to first manually prepare the dataset to a bucket. I guess MOUNT mode would be the most ideal if it works.

```
resources:
  cloud: gcp

file_mounts:
  /tensorflow-datasets:
    name: sky-tpu-tfds
    mode: MOUNT

setup: |
  echo export TFDS_DATA_DIR=/tensorflow-datasets >> ~/.bashrc
  pip install tensorflow_datasets tensorflow

run: |
  python -c "import tensorflow_datasets as tfds; tfds.load('cifar10')"
```

**Comment by Michaelvll** [comment]
> Yes I prepare a minimal example to reproduce it. Hope it helps! COPY mode should work but it will require an additional step to first manually prepare the dataset to a bucket. I guess MOUNT mode would be the most ideal if it works.

Do we need to set the target path in the `tfds.load()` to the mounted storage?

**Comment by infwinston** [comment]
> > Yes I prepare a minimal example to reproduce it. Hope it helps! COPY mode should work but it will require an additional step to first manually prepare the dataset to a bucket. I guess MOUNT mode would be the most ideal if it works.
> 
> Do we need to set the target path in the `tfds.load()` to the mounted storage?

By default it'd use env variable `TFDS_DATA_DIR` which I set in the `SETUP` section.

**Comment by romilbhardwaj** [comment]
Small update - I was able to replicate this issue. It works fine if I force `store: s3`, so this appears to be a gcsfuse issue. Investigating more
