### ISSUE TITLE
[Dependency] dependency issue with `awscli` when ray==2.0.1 used locally

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1321]
The issue was initially reported by @infwinston in https://github.com/skypilot-org/skypilot/pull/1133#issuecomment-1291210395

After upgrading ray to `2.0.1` locally (`pip install "ray[default]==2.0.1"`), some of the skypilot commands fail due to dependency issues:
```
sky storage delete skypilot-filemounts-*      
Deleting 120 storage objects.
Deleting storage object 'skypilot-filemounts-folder-zhwu-38e7582c-1'.
I 10-29 00:34:08 storage.py:402] Detected existing storage object, loading Storage: skypilot-filemounts-folder-zhwu-38e7582c-1
Traceback (most recent call last):
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (colorama 0.4.5 (/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/ray/thirdparty_files), Requirement.parse('colorama<0.4.5,>=0.2.5'), {'awscli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhwu/miniconda3/envs/sky-dev/bin/sky", line 33, in <module>
    sys.exit(load_entry_point('skypilot', 'console_scripts', 'sky')())
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/utils/common_utils.py", line 179, in _record
    return f(*args, **kwargs)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/cli.py", line 911, in invoke
    return super().invoke(ctx)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/utils/common_utils.py", line 179, in _record
    return f(*args, **kwargs)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/cli.py", line 911, in invoke
    return super().invoke(ctx)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/utils/common_utils.py", line 200, in _record
    return f(*args, **kwargs)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/cli.py", line 2534, in storage_delete
    sky.storage_delete(name)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/utils/common_utils.py", line 200, in _record
    return f(*args, **kwargs)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/core.py", line 757, in storage_delete
    store_object = data.Storage(name=handle.storage_name,
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/data/storage.py", line 411, in __init__
    store = GcsStore.from_metadata(s_metadata,
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/data/storage.py", line 172, in from_metadata
    return cls(name=override_args.get('name', metadata.name),
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/data/storage.py", line 1031, in __init__
    super().__init__(name, source, region, is_sky_managed)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/data/storage.py", line 163, in __init__
    self.initialize()
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/data/storage.py", line 1058, in initialize
    self.client = gcp.storage_client()
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/adaptors/gcp.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhwu/Library/CloudStorage/OneDrive-Personal/AResource/PhD/Research/sky-computing/code/sky-experiment-dev/sky/adaptors/gcp.py", line 46, in storage_client
    from google.cloud import storage
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/google/cloud/storage/batch.py", line 30, in <module>
    from google.cloud import exceptions
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/google/cloud/exceptions/__init__.py", line 24, in <module>
    from google.api_core import exceptions
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/google/api_core/exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/google/rpc/__init__.py", line 18, in <module>
    import pkg_resources
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (colorama 0.4.5 (/Users/zhwu/miniconda3/envs/sky-dev/lib/python3.8/site-packages/ray/thirdparty_files), Requirement.parse('colorama<0.4.5,>=0.2.5'), {'awscli'})
```

**Comment by infwinston** [comment]
Thanks for the fix!
