### ISSUE TITLE
[Azure] Launching the azure cluster can cause nondeterministic error

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1332]
`sky launch -y -c launch-azure examples/azure_start_stop.yaml` sometimes getting the following issue:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/sky/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 153, in run
    self.do_update()
  File "/home/ubuntu/.conda/envs/sky/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 327, in do_update
    self.wait_ready(deadline)
  File "/home/ubuntu/.conda/envs/sky/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 271, in wait_ready
    if self.provider.is_terminated(self.node_id):
  File "/home/ubuntu/skypilot/sky/skylet/providers/azure/node_provider.py", line 166, in is_terminated
    node = self._get_node(node_id=node_id)
  File "/home/ubuntu/skypilot/sky/skylet/providers/azure/node_provider.py", line 361, in _get_node
    return self.cached_nodes[node_id]
KeyError: 'ray-test-azure-start-stop-3446f302-c9-head-492094d10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/sky/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.conda/envs/sky/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 155, in run
    self.provider.set_node_tags(
  File "/home/ubuntu/skypilot/sky/skylet/providers/azure/node_provider.py", line 38, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ubuntu/skypilot/sky/skylet/providers/azure/node_provider.py", line 266, in set_node_tags
    node_tags = self._get_cached_node(node_id)["tags"]
  File "/home/ubuntu/skypilot/sky/skylet/providers/azure/node_provider.py", line 366, in _get_cached_node
    return self._get_node(node_id=node_id)
  File "/home/ubuntu/skypilot/sky/skylet/providers/azure/node_provider.py", line 361, in _get_node
    return self.cached_nodes[node_id]
KeyError: 'ray-test-azure-start-stop-3446f302-c9-head-492094d10'
2022-10-30 04:21:36,033 PANIC commands.py:813 -- Failed to setup head node.
Error: Failed to setup head node.
```

@suquark Do you think this is a bug in our `node_provider`?

I tried to get the `resources_group` with the code in `self.provider.is_terminated(self.node_id)` above to get an existing `resource_group` but it fails. However, `az vm list --resource-group test-azure-start-stop-3446f302-c9-eastus` can get the correct cluster. Do you have any idea of the issue @suquark ?
```
>>> with open('/home/ubuntu//.sky/generated/test-azure-start-stop-3446f302-c9.yml', 'r') as f:
...     config = yaml.safe_load(f.read())
...
>>> from sky.skylet.providers.azure.node_provider import AzureNodeProvider
>>> provider = AzureNodeProvider(config['provider'], config['cluster_name'])
>>> vms = provider.compute_client.virtual_machines.list(resource_group_name=provider.provider_config['resource_group'])
>>> list(vms)
[]
```

**Comment by Michaelvll** [comment]
Just identified the issue, I was launching the azure cluster from an AWS ec2 VM, where there are some empty Azure credential services set up by default. We can limit the credential used by the `node_provider` to be only `AzureCliCredential` instead of a chain of different kind of credentials (fixed in #1330)
