### ISSUE TITLE
[Onprem] Ray up Error

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1355]
Ray up the generated YAML file for Sky Onprem has the following error in the logs. After some deeper investigation, it seems to be caused by this PR here: https://github.com/skypilot-org/skypilot/commit/1407509f48baaf154e62297e734cbc3f571a83e0 This is because the generated Ray YAML file is populated with the incorrect filemounts.

Logs:
```
Traceback (most recent call last):
  File "/Users/michaelluo/opt/anaconda3/envs/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2339, in main
    return cli()
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1194, in up
    use_login_shells=use_login_shells,
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 284, in create_or_update_cluster
    no_monitor_on_head,
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 754, in get_or_create_head_node
    config["file_mounts"], None, config
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 425, in hash_runtime_conf
    add_content_hashes(local_path)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 415, in add_content_hashes
    add_hash_of_file(path)
  File "/Users/michaelluo/opt/anaconda3/envs/ray/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 397, in add_hash_of_file
    with open(fpath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/michaelluo/.sky/generated/wtf.yml.tmp'
```

**Comment by michaelzhiluo** [comment]
This issue is resolved.
