### ISSUE TITLE
[Onprem] Unable to launch any task -  No such file or directory: .../<clus>.yml.tmp

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1388]
I create a cluster with  the launch script
```
$ python examples/local/launch_cloud_onprem.py localclus
```

Then I try to run a simple echo task. Fails with `No such file or directory`:
```
(base) romilb@romilbx1yoga:/mnt/d/Romil/Berkeley/Research/sky-experiments/examples/local$ sky launch -c localclus -- echo hi
Task from command: echo hi
I 11-10 11:30:39 optimizer.py:605] == Optimizer ==
I 11-10 11:30:39 optimizer.py:628] Estimated cost: $0.0 / hour
I 11-10 11:30:39 optimizer.py:628]
I 11-10 11:30:39 optimizer.py:685] Considered resources (1 node):
I 11-10 11:30:39 optimizer.py:713] ---------------------------------------------------------------
I 11-10 11:30:39 optimizer.py:713]  CLOUD   INSTANCE   vCPUs   ACCELERATORS   COST ($)   CHOSEN
I 11-10 11:30:39 optimizer.py:713] ---------------------------------------------------------------
I 11-10 11:30:39 optimizer.py:713]  Local   on-prem    -       -              0.00          ✔
I 11-10 11:30:39 optimizer.py:713] ---------------------------------------------------------------
I 11-10 11:30:39 optimizer.py:713]
Initializing local cluster 'localclus'. Proceed? [Y/n]: Y
I 11-10 11:30:40 cloud_vm_ray_backend.py:2753] Connecting to local cluster: 'localclus' [Username: test].
I 11-10 11:30:40 cloud_vm_ray_backend.py:2753] Run `sky status` to see existing clusters.
I 11-10 11:30:40 cloud_vm_ray_backend.py:919] To view detailed progress: tail -n100 -f /home/romilb/sky_logs/sky-2022-11-10-11-30-38-456322/provision.log
I 11-10 11:30:43 cloud_vm_ray_backend.py:1176] Launching on local cluster 'localclus'.
I 11-10 11:30:54 cloud_vm_ray_backend.py:660] ====== stdout ======
2022-11-10 11:30:53,950 INFO commands.py:270 -- Cluster: localclus
2022-11-10 11:30:53,966 INFO commands.py:349 -- Checking Local environment settings
2022-11-10 11:30:54,079 INFO commands.py:649 -- No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]
2022-11-10 11:30:54,079 INFO commands.py:699 -- Acquiring an up-to-date head node
2022-11-10 11:30:54,081 INFO commands.py:715 -- Launched a new head node
2022-11-10 11:30:54,081 INFO commands.py:719 -- Fetching the new head node
2022-11-10 11:30:54,082 INFO commands.py:738 -- <1/1> Setting up head node

I 11-10 11:30:54 cloud_vm_ray_backend.py:663] ====== stderr ======
Usage stats collection will be enabled by default in the next release. See https://github.com/ray-project/ray/issues/20857 for more details.
2022-11-10 11:30:54,077 INFO node_provider.py:46 -- Head IP changed - recreating cluster.
2022-11-10 11:30:54,077 INFO node_provider.py:50 -- ClusterState: Loaded cluster state: []
2022-11-10 11:30:54,081 INFO node_provider.py:112 -- ClusterState: Writing cluster state: ['52.90.164.143']
Traceback (most recent call last):
  File "/mnt/d/wsl/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2269, in main
    return cli()
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1168, in up
    use_login_shells=use_login_shells,
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 283, in create_or_update_cluster
    no_monitor_on_head,
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 747, in get_or_create_head_node
    config["file_mounts"], None, config
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 425, in hash_runtime_conf
    add_content_hashes(local_path)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 415, in add_content_hashes
    add_hash_of_file(path)
  File "/mnt/d/wsl/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 397, in add_hash_of_file
    with open(fpath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/romilb/.sky/generated/localclus.yml.tmp'

Clusters
NAME                   LAUNCHED     RESOURCES            STATUS  AUTOSTOP  COMMAND                       
onprem-cluster-862229  17 mins ago  1x AWS(m6i.2xlarge)  UP      -         launch_cloud_onprem.py lo...

Local clusters:
NAME       USER  HEAD_IP        RESOURCES    COMMAND
localclus  test  52.90.164.143  [(no GPUs)]  sky launch -c localclus --...

RuntimeError: Errors occurred during launching of cluster services; check logs above.
```

Logs from the launch script, if it's helpful:
```
$ python examples/local/launch_cloud_onprem.py localclus
I 11-10 11:09:54 optimizer.py:605] == Optimizer ==
I 11-10 11:09:54 optimizer.py:628] Estimated cost: $0.4 / hour
I 11-10 11:09:54 optimizer.py:628]
I 11-10 11:09:54 optimizer.py:685] Considered resources (1 node):
I 11-10 11:09:54 optimizer.py:713] ------------------------------------------------------------------
I 11-10 11:09:54 optimizer.py:713]  CLOUD   INSTANCE      vCPUs   ACCELERATORS   COST ($)   CHOSEN
I 11-10 11:09:54 optimizer.py:713] ------------------------------------------------------------------
I 11-10 11:09:54 optimizer.py:713]  AWS     m6i.2xlarge   8       -              0.38          ✔
I 11-10 11:09:54 optimizer.py:713] ------------------------------------------------------------------
I 11-10 11:09:54 optimizer.py:713]
I 11-10 11:09:54 cloud_vm_ray_backend.py:2759] Creating a new cluster: "onprem-cluster-862229" [1x AWS(m6i.2xlarge)].
I 11-10 11:09:54 cloud_vm_ray_backend.py:2759] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 11-10 11:10:06 cloud_vm_ray_backend.py:919] To view detailed progress: tail -n100 -f /home/romilb/sky_logs/sky-2022-11-10-11-09-53-312694/provision.log
I 11-10 11:10:09 cloud_vm_ray_backend.py:1180] Launching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f)
I 11-10 11:11:51 log_utils.py:45] Head node is up.
I 11-10 11:13:04 cloud_vm_ray_backend.py:1014] Successfully provisioned or found existing VM.
I 11-10 11:13:06 cloud_vm_ray_backend.py:2803] Processing file mounts.
I 11-10 11:13:06 cloud_vm_ray_backend.py:2833] To view detailed progress: tail -n100 -f ~/sky_logs/sky-2022-11-10-11-09-53-312694/file_mounts.log
I 11-10 11:13:06 backend_utils.py:1074] Syncing (to 1 node): ~/.ssh/sky-key.pub -> ~/.sky/file_mounts/user-key
I 11-10 11:13:08 cloud_vm_ray_backend.py:2035] Running setup on 1 node.
Adding user `test' ...
Adding new group `test' (1001) ...
Adding new user `test' (1001) with group `test' ...
Creating home directory `/home/test' ...
Copying files from `/etc/skel' ...
I 11-10 11:13:10 cloud_vm_ray_backend.py:2038] Setup completed.
I 11-10 11:13:10 cloud_vm_ray_backend.py:2213] Run commands not specified or empty.
I 11-10 11:13:10 cloud_vm_ray_backend.py:2242]
I 11-10 11:13:10 cloud_vm_ray_backend.py:2242] Cluster name: onprem-cluster-862229
I 11-10 11:13:10 cloud_vm_ray_backend.py:2242] To log into the head VM: ssh onprem-cluster-862229
I 11-10 11:13:10 cloud_vm_ray_backend.py:2242] To submit a job:         sky exec onprem-cluster-862229 yaml_file
I 11-10 11:13:10 cloud_vm_ray_backend.py:2242] To stop the cluster:     sky stop onprem-cluster-862229
I 11-10 11:13:10 cloud_vm_ray_backend.py:2242] To teardown the cluster: sky down onprem-cluster-862229
Clusters
NAME                   LAUNCHED        RESOURCES            STATUS  AUTOSTOP  COMMAND
onprem-cluster-862229  a few secs ago  1x AWS(m6i.2xlarge)  UP      -         launch_cloud_onprem.py lo...
myclus                 6 mins ago      docker               UP      -         sky launch -c myclus exam...
[1/4] Installing on-premise dependencies
[2/4] Auto-detecting cluster resources
[3/4] Launching sky runtime
[4/4] Generating sanitized local yaml file
Saved in ~/.sky/local/localclus.yml 
Successfully deployed local cluster 'localclus'

Sky onprem cluster localclus is now ready for use! You can launch jobs with `sky launch -c localclus -- [CMD].` After you are done, shut down the cluster by running `sky down localclus onprem-cluster-8622
29` and removing the local cluster config in ~/.sky/local/localclus.yml.
(base) romilb@romilbx1yoga:/mnt/d/Romil/Berkeley/Research/sky-experiments/examples/local$ sky launch -c localclus -- ^C
(base) romilb@romilbx1yoga:/mnt/d/Romil/Berkeley/Research/sky-experiments/examples/local$ sky status
Clusters
NAME                   LAUNCHED     RESOURCES            STATUS  AUTOSTOP  COMMAND
onprem-cluster-862229  17 mins ago  1x AWS(m6i.2xlarge)  UP      -         launch_cloud_onprem.py lo...
```

My `.sky/generated` dir:
```
(base) romilb@romilbx1yoga:/mnt/d/Softwares/cmder$ ls /home/romilb/.sky/generated/
localclus.yml  onprem-cluster-862229.yml 
```

**Comment by infwinston** [comment]
hmm I thought this PR solves it? or did we miss anything
https://github.com/skypilot-org/skypilot/pull/1356/files#diff-5d3b8c053073eef6241a9fc4439b8e97c680e73e6dbfe01a587eea2bf0000c4dR790

**Comment by romilbhardwaj** [comment]
Ah my bad - I was on a stale branch. It indeed works after #1356.
