### ISSUE TITLE
[Provisioner] Sky Launch hangs when network is not available

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1460]
I put my laptop in airplane mode and tried `sky launch`. It should have thrown an error early instead of indefinitely (15min+) retrying. Related to, but different from #1232, where only ssh was blocked. Here no network is available. 

```
(base) romilb@romilbx1yoga:/mnt/d/Romil/Berkeley/Research/sky-experiments$ sky launch -- echo hi
Task from command: echo hi
I 11-28 08:43:57 optimizer.py:606] == Optimizer ==
I 11-28 08:43:57 optimizer.py:618] Target: minimizing cost       
I 11-28 08:43:57 optimizer.py:629] Estimated cost: $0.4 / hour   
I 11-28 08:43:57 optimizer.py:714]  CLOUD   INSTANCE         vCPUs   ACCELERATORS   COST ($)   CHOSEN
I 11-28 08:43:57 optimizer.py:714] ---------------------------------------------------------------------
I 11-28 08:43:57 optimizer.py:714]  AWS     m6i.2xlarge      8       -              0.38          ✔
I 11-28 08:43:57 optimizer.py:714]  Azure   Standard_D8_v4   8       -              0.38
I 11-28 08:43:57 optimizer.py:714]  GCP     n1-highmem-8     8       -              0.47
I 11-28 08:43:57 optimizer.py:714] ---------------------------------------------------------------------
I 11-28 08:43:57 optimizer.py:714]
Launching a new cluster 'sky-236f-romilb'. Proceed? [Y/n]: Y
I 11-28 08:44:03 cloud_vm_ray_backend.py:2852] Creating a new cluster: "sky-236f-romilb" [1x AWS(m6i.2xlarge)].
I 11-28 08:44:03 cloud_vm_ray_backend.py:2852] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
<was stuck here for two minutes>
I 11-28 08:46:09 cloud_vm_ray_backend.py:988] To view detailed progress: tail -n100 -f /home/romilb/sky_logs/sky-2022-11-28-08-43-53-532751/provision.log
I 11-28 08:46:09 cloud_vm_ray_backend.py:1249] Launching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f)
<stuck on the "Launching" spinner for 15 min till ctrl+c>
```

**Comment by romilbhardwaj** [comment]
Should keep open. Still fails with a cryptic error, even though its a simple network connectivity issue:

```
(base) ➜  ~ SKYPILOT_DEBUG=0 sky launch -- echo hi
Task from command: echo hi
I 06-08 10:03:05 optimizer.py:636] == Optimizer ==
I 06-08 10:03:05 optimizer.py:647] Target: minimizing cost
I 06-08 10:03:05 optimizer.py:659] Estimated cost: $0.4 / hour
I 06-08 10:03:05 optimizer.py:659]
I 06-08 10:03:05 optimizer.py:732] Considered resources (1 node):
I 06-08 10:03:05 optimizer.py:781] -----------------------------------------------------------------------------------------------
I 06-08 10:03:05 optimizer.py:781]  CLOUD    INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 06-08 10:03:05 optimizer.py:781] -----------------------------------------------------------------------------------------------
I 06-08 10:03:05 optimizer.py:781]  AWS      m6i.2xlarge       8       32        -              us-east-1     0.38          ✔
I 06-08 10:03:05 optimizer.py:781]  Azure    Standard_D8s_v5   8       32        -              eastus        0.38
I 06-08 10:03:05 optimizer.py:781]  IBM      bx2-8x32          8       32        -              us-east       0.38
I 06-08 10:03:05 optimizer.py:781]  GCP      n2-standard-8     8       32        -              us-central1   0.39
I 06-08 10:03:05 optimizer.py:781]  Lambda   gpu_1x_a10        30      200       A10:1          us-east-1     0.60
I 06-08 10:03:05 optimizer.py:781] -----------------------------------------------------------------------------------------------
I 06-08 10:03:05 optimizer.py:781]
Launching a new cluster 'sky-e2c7-romilb'. Proceed? [Y/n]: Y
I 06-08 10:03:07 cloud_vm_ray_backend.py:3746] Creating a new cluster: "sky-e2c7-romilb" [1x AWS(m6i.2xlarge)].
I 06-08 10:03:07 cloud_vm_ray_backend.py:3746] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
W 06-08 10:03:16 cloud_vm_ray_backend.py:1921] sky.exceptions.CloudUserIdentityError: Failed to get AWS user.
W 06-08 10:03:16 cloud_vm_ray_backend.py:1921]   Reason: [botocore.exceptions.EndpointConnectionError] Could not connect to the endpoint URL: "https://sts.amazonaws.com/".
W 06-08 10:03:16 cloud_vm_ray_backend.py:1946]
W 06-08 10:03:16 cloud_vm_ray_backend.py:1946] Provision failed for 1x AWS(m6i.2xlarge) in us-east-1. Trying other locations (if any).
I 06-08 10:03:16 optimizer.py:636] == Optimizer ==
I 06-08 10:03:16 optimizer.py:647] Target: minimizing cost
I 06-08 10:03:16 optimizer.py:659] Estimated cost: $0.4 / hour
I 06-08 10:03:16 optimizer.py:659]
I 06-08 10:03:16 optimizer.py:732] Considered resources (1 node):
I 06-08 10:03:16 optimizer.py:781] -----------------------------------------------------------------------------------------------
I 06-08 10:03:16 optimizer.py:781]  CLOUD    INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 06-08 10:03:16 optimizer.py:781] -----------------------------------------------------------------------------------------------
I 06-08 10:03:16 optimizer.py:781]  Azure    Standard_D8s_v5   8       32        -              eastus        0.38          ✔
I 06-08 10:03:16 optimizer.py:781]  IBM      bx2-8x32          8       32        -              us-east       0.38
I 06-08 10:03:16 optimizer.py:781]  GCP      n2-standard-8     8       32        -              us-central1   0.39
I 06-08 10:03:16 optimizer.py:781]  Lambda   gpu_1x_a10        30      200       A10:1          us-east-1     0.60
I 06-08 10:03:16 optimizer.py:781] -----------------------------------------------------------------------------------------------
I 06-08 10:03:16 optimizer.py:781]
I 06-08 10:03:16 cloud_vm_ray_backend.py:1333] To view detailed progress: tail -n100 -f /Users/romilb/sky_logs/sky-2023-06-08-10-03-00-888153/provision.log
I 06-08 10:03:16 cloud_vm_ray_backend.py:1657] Launching on Azure eastus
I 06-08 10:03:18 cloud_vm_ray_backend.py:817] ====== stdout ======
2023-06-08 10:03:17,312	INFO commands.py:276 -- Cluster: sky-e2c7-romilb
2023-06-08 10:03:17,875	INFO commands.py:353 -- Checking External environment settings
I 06-08 10:03:17 config.py:57] Using subscription id: aa86df77-e703-453e-b2f4-955c3b33e534
I 06-08 10:03:17 config.py:72] Creating/Updating resource group: sky-e2c7-romilb-eastus

I 06-08 10:03:18 cloud_vm_ray_backend.py:820] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
AzureCliCredential.get_token failed: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /b9d92ecb-94ef-4318-af02-95665c9a2c5b/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /b9d92ecb-94ef-4318-af02-95665c9a2c5b/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 66, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 382, in get_raw_token
    credential = self._create_credential(account, tenant)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 592, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 225, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/auth/msal_authentication.py", line 45, in __init__
    super().__init__(client_id, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/application.py", line 1685, in __init__
    super(PublicClientApplication, self).__init__(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/application.py", line 533, in __init__
    self.authority = Authority(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/authority.py", line 120, in __init__
    openid_config = tenant_discovery(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/authority.py", line 175, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /b9d92ecb-94ef-4318-af02-95665c9a2c5b/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 169, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/romilb/tools/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource https://management.azure.com']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/98/hhq8wrtx6y13196q61xphjsm0000gn/T/skypilot_ray_up_z6s86r8r.py", line 76, in <module>
    sdk.create_or_update_cluster('/Users/romilb/.sky/generated/sky-e2c7-romilb.yml', **{'no_restart': True})
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 279, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 381, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/skylet/providers/azure/node_provider.py", line 421, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/skylet/providers/azure/config.py", line 40, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/skylet/providers/azure/config.py", line 76, in _configure_resource_group
    rg_create_or_update(resource_group_name=resource_group, parameters=params)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_operations.py", line 9802, in create_or_update
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 205, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
    response = self.next.send(request)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 474, in send
    response = self.next.send(request)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 115, in send
    self.on_request(request)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 92, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 99, in get_token
    output = _run_command(command, self._process_timeout)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 183, in _run_command
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /b9d92ecb-94ef-4318-af02-95665c9a2c5b/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /b9d92ecb-94ef-4318-af02-95665c9a2c5b/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 66, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 382, in get_raw_token
    credential = self._create_credential(account, tenant)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 592, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 225, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/azure/cli/core/auth/msal_authentication.py", line 45, in __init__
    super().__init__(client_id, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/application.py", line 1685, in __init__
    super(PublicClientApplication, self).__init__(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/application.py", line 533, in __init__
    self.authority = Authority(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/authority.py", line 120, in __init__
    openid_config = tenant_discovery(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/authority.py", line 175, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /b9d92ecb-94ef-4318-af02-95665c9a2c5b/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103059550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`


Clusters
NAME             LAUNCHED        RESOURCES                  STATUS  AUTOSTOP  COMMAND
sky-e2c7-romilb  a few secs ago  1x Azure(Standard_D8s_v5)  INIT    -         sky launch -- echo hi
sky-0ca1-romilb  47 secs ago     1x Azure(Standard_D8s_v5)  INIT    -         sky launch -- echo hi

RuntimeError: Errors occurred during provision; check logs above.
```
