### ISSUE TITLE
`sky status` throws `TypeError: 'in <string>' requires string as left operand, not NoneType`

### ISSUE THREAD

**Issue by pschafhalter** [skypilot-org/skypilot#1589]
To reproduce, run `sky status`.

Skypilot version: 0.2.2
OS: Ubuntu 22.04.1 LTS
Python version: 3.10.6
Active clouds: AWS, GCP

The following line causes the error. The value of `self.image_id` is "ami-0fe5af21074ad2a10" (a string). Checking if `None` is in a string throws a `TypeError`.
https://github.com/skypilot-org/skypilot/blob/ad6296b71f8c6dde35ed47083e920606fb4e1b00/sky/resources.py#L140

Full error:
```
Traceback (most recent call last):
  File "/home/peter/workspace/cloud-av-workloads/env/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/utils/common_utils.py", line 217, in _record
    return f(*args, **kwargs)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/cli.py", line 994, in invoke
    return super().invoke(ctx)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/utils/common_utils.py", line 238, in _record
    return f(*args, **kwargs)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/cli.py", line 1426, in status
    num_pending_autostop += status_utils.show_status_table(
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/utils/cli_utils/status_utils.py", line 91, in show_status_table
    row.append(status_column.calc(record))
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/utils/cli_utils/status_utils.py", line 48, in calc
    val = self.calc_func(record)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/utils/cli_utils/status_utils.py", line 234, in _get_resources
    launched_resource_str = str(handle.launched_resources)
  File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/resources.py", line 141, in __repr__
    if None in self.image_id:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Comment by Michaelvll** [comment]
Hey @pschafhalter, thank you for filing the issue! Just to clarify it, is the cluster raising the error a cluster launched with a previous version of SkyPilot?

**Comment by pschafhalter** [comment]
Yes, I believe that is the case. The error no longer occurs after terminating the instances via the AWS web interface and running `rm -rf ~/.sky`.

**Comment by Michaelvll** [comment]
Thanks! It is nice that you don't need the states anymore. I also just submitted a PR #1590 to fix the backward compatibility issue, so that removing the `~/.sky` folder is not needed. A reproducible snippet:
```
pip install skypilot==0.2.1
sky launch -c old --image-id projects/deeplearning-platform-release/global/images/common-cpu-v20220806
pip install -e . # install the latest skypilot
sky status
```
