### ISSUE TITLE
[GCP] Better error handling/documentation if there are no subnets

### ISSUE THREAD

**Issue by pschafhalter** [skypilot-org/skypilot#1591]
Hi,

GCP requires a subnet before a user can launch an instance. If there are no existing subnets, launching a cluster (e.g. via `sky gpunode --cloud=gcp`) fails with an error (see below). I recommend adding a note in the [installation section of the docs](https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#cloud-account-setup), or throwing a more informative error suggesting that the user creates a subnet.

Error:
```
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922] Traceback (most recent call last):
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/bin/ray", line 8, in <module>
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     sys.exit(main())
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2339, in main
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return cli()
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return self.main(*args, **kwargs)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1053, in main
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     rv = self.invoke(ctx)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return _process_result(sub_ctx.command.invoke(sub_ctx))
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return ctx.invoke(self.callback, **ctx.params)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return __callback(*args, **kwargs)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return f(*args, **kwargs)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/ray/scripts/scripts.py", line 1223, in down
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     teardown_cluster(
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 401, in teardown_cluster
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     config = _bootstrap_config(config)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 376, in _bootstrap_config
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     resolved_config = provider_cls.bootstrap_config(config)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/skylet/providers/gcp/node_provider.py", line 303, in bootstrap_config
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return bootstrap_gcp(cluster_config)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/skylet/providers/gcp/config.py", line 288, in bootstrap_gcp
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     config = _configure_subnet(config, compute)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/skylet/providers/gcp/config.py", line 509, in _configure_subnet
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     subnets = _list_subnets(config, compute)
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]   File "/home/peter/workspace/cloud-av-workloads/env/lib/python3.10/site-packages/sky/skylet/providers/gcp/config.py", line 557, in _list_subnets
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922]     return response["items"]
E 01-13 14:04:37 cloud_vm_ray_backend.py:2922] KeyError: 'items'
```
`response` contains:
```{'kind': 'compute#subnetworkList', 'id': 'projects/$PROJECT_NAME/regions/us-central1/subnetworks', 'selfLink': 'https://www.googleapis.com/compute/v1/projects/$PROJECT_NAME/regions/us-central1/subnetworks'}```

**Comment by infwinston** [comment]
@pschafhalter thanks a lot for raising the issue! we'll investigate and add them into docs.

**Comment by infwinston** [comment]
@pschafhalter Looks like a default subnet should be added by GCP when enabling the Compute Engine API, which is needed for managing VMs.
https://console.cloud.google.com/marketplace/details/google/compute.googleapis.com

`sky check` would hint and help enabling those APIs. You may try it and see if that works. We should also clarify this in the doc. 
```
(sky-tmp) weichiang@mbp sky % sky check
Checking credentials to enable clouds for SkyPilot.
  AWS: enabled
  Azure: enabled
  Checking GCP...
Enabling Compute Engine API (free of charge; this may take a minute)...
Done. Took 63.5 secs.

Hint: Enabled GCP API(s) may take a few minutes to take effect. If any SkyPilot commands/calls failed, retry after some time.
  GCP: enabled

SkyPilot will use only the enabled clouds to run tasks. To change this, configure cloud credentials, and run sky check.
If any problems remain, please file an issue at https://github.com/skypilot-org/skypilot/issues/new
```

**Comment by pschafhalter** [comment]
Interesting, `sky check` check worked fine for me, but there were no subnets when I checked via the web API. For reference, I'm running Google Cloud SDK 413.0.0.

**Comment by infwinston** [comment]
hmm that's not expected. From GCP's doc, each project should come with a default VPC network. https://cloud.google.com/vpc/docs/vpc#org-policies

I tried to create a new project and ran `sky check`. Looks like a VPC network is created afterwards.
Not sure if our organization policy disables such default net creation by `compute.skipDefaultNetworkCreation`..

**Comment by infwinston** [comment]
@pschafhalter We are investigating why the default is missing.
Meanwhile, if manually creating one is needed, the default vpc network comes with the following four rules. 

https://cloud.google.com/vpc/docs/firewalls#more_rules_default_vpc
```
default-allow-internal | ingress | 65534 | 10.128.0.0/9 | allow | tcp:0-65535udp:0-65535icmp | Permits incoming connections to VM instances from other instances within the same VPC network.
default-allow-ssh | ingress | 65534 | 0.0.0.0/0 | allow | tcp:22 | Lets you connect to instances with tools such as ssh, scp, or sftp.
default-allow-rdp | ingress | 65534 | 0.0.0.0/0 | allow | tcp:3389 | Lets you connect to instances using the Microsoft Remote Desktop Protocol (RDP).
default-allow-icmp | ingress | 65534 | 0.0.0.0/0 | allow | icmp | Lets you use tools such as ping.
```
Would appreciate if you could let us know whether `sky launch` works after this, thanks :)

**Comment by pschafhalter** [comment]
I manually created a subnet via the web interface and `sky launch` worked afterwards. Thanks for the help.
