### ISSUE TITLE
Sky launch fails on GCP if there is no default network

### ISSUE THREAD

**Issue by franklsf95** [skypilot-org/skypilot#1597]
Hi,

I installed Skypilot on a fresh Python environment on Mac, ran `sky check` and got GCP set up; now I wrote a simple YAML and `sky launch -c sky sky.yaml`, and this happened:

```
 ~/Dropbox/a/spatial_omics/github/bmp   main ?  sky launch -c bmp sky.yaml                                                 ✔  785  16:41:36
Task from YAML spec: sky.yaml
I 01-15 16:42:00 optimizer.py:606] == Optimizer ==
I 01-15 16:42:00 optimizer.py:617] Target: minimizing cost
I 01-15 16:42:00 optimizer.py:629] Estimated cost: $3.0 / hour
I 01-15 16:42:00 optimizer.py:629]
I 01-15 16:42:00 optimizer.py:692] Considered resources (1 node):
I 01-15 16:42:00 optimizer.py:740] ---------------------------------------------------------------------------------
I 01-15 16:42:00 optimizer.py:740]  CLOUD   INSTANCE       vCPUs   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 01-15 16:42:00 optimizer.py:740] ---------------------------------------------------------------------------------
I 01-15 16:42:00 optimizer.py:740]  GCP     n1-highmem-8   8       V100:1         us-central1   2.95          ✔
I 01-15 16:42:00 optimizer.py:740] ---------------------------------------------------------------------------------
I 01-15 16:42:00 optimizer.py:740]
Launching a new cluster 'bmp'. Proceed? [Y/n]:
I 01-15 16:42:06 cloud_vm_ray_backend.py:3099] Creating a new cluster: "bmp" [1x GCP(n1-highmem-8, {'V100': 1})].
I 01-15 16:42:06 cloud_vm_ray_backend.py:3099] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 01-15 16:42:09 cloud_vm_ray_backend.py:1076] To view detailed progress: tail -n100 -f /Users/ab/sky_logs/sky-2023-01-15-16-41-59-229974/provision.log
I 01-15 16:42:17 cloud_vm_ray_backend.py:1377] Launching on GCP us-central1 (us-central1-a)
I 01-15 16:42:22 cloud_vm_ray_backend.py:695] ====== stdout ======
2023-01-15 16:42:18,366	INFO commands.py:276 -- Cluster: bmp
2023-01-15 16:42:18,668	INFO commands.py:353 -- Checking External environment settings

I 01-15 16:42:22 cloud_vm_ray_backend.py:698] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
Traceback (most recent call last):
  File "/var/folders/p9/l9_cp9p96kg_0zk6v9v47ly00000gn/T/skypilot_ray_up_mhs8toku.py", line 42, in <module>
    sdk.create_or_update_cluster('/Users/ab/.sky/generated/bmp.yml', **{'no_restart': True})
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 279, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 381, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/sky/skylet/providers/gcp/node_provider.py", line 303, in bootstrap_config
    return bootstrap_gcp(cluster_config)
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/sky/skylet/providers/gcp/config.py", line 288, in bootstrap_gcp
    config = _configure_subnet(config, compute)
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/sky/skylet/providers/gcp/config.py", line 509, in _configure_subnet
    subnets = _list_subnets(config, compute)
  File "/Users/ab/opt/miniconda3/envs/omics/lib/python3.9/site-packages/sky/skylet/providers/gcp/config.py", line 555, in _list_subnets
    return response["items"]
KeyError: 'items'

Clusters
NAME  LAUNCHED        RESOURCES                          STATUS  AUTOSTOP  COMMAND
bmp   a few secs ago  1x GCP(n1-highmem-8, {'V100': 1})  INIT    -         sky launch -c bmp sky.yam...

RuntimeError: Errors occurred during provision; check logs above.
```

EDIT: Found the reason. When I tried to create the VM manually, GCP prompts "you have no default VPC/network". It worked after I created a VPC. Would be helpful to surface this to the user.

EDIT 2: After creation, it got stuck in SSH, because the default network did not allow SSH port (22). Manually adding a firewall rule fixed this.

**Comment by Michaelvll** [comment]
Thanks for filing the issue @franklsf95! Linking the issue #1591 with the same problem. @infwinston is adding the functionality to automatically create the subnets in #1594. Please stay tuned. : )

**Comment by infwinston** [comment]
Yes, the PR will include both VPC creation and essential firewall rules. We'll fix it asap.
