### ISSUE TITLE
`sky launch` fails when rsync is not installed in the custom image

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1603]
A user reported that the following error happens when the custom image that does not have rsync installed.

```
2023-01-17 19:54:53,855 INFO updater.py:239 -- [2/7] Processing file mounts
2023-01-17 19:54:53,855 VINFO command_runner.py:552 -- Running `mkdir -p ~/.sky/.runtime_files`
2023-01-17 19:54:53,855 VVINFO command_runner.py:554 -- Full command is `ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_638d9623ae/817f824242/%C -o ControlPersist=10s -o ConnectTimeout=120s gcpuser@34.72.143.188 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~/.sky/.runtime_files)'`
2023-01-17 19:54:54,953 VINFO command_runner.py:595 -- Running `rsync --rsh ssh -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_638d9623ae/817f824242/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz /var/folders/bx/cnr_jmsj4n79c9p0q4v68xvw0000gp/T/tmpevfl22c_/ gcpuser@34.72.143.188:~/.sky/.runtime_files/`
2023-01-17 19:54:55,056 INFO log_timer.py:25 -- NodeUpdater: ray-test-no-rsyc-image-head-5615c63a-compute: Synced /var/folders/bx/cnr_jmsj4n79c9p0q4v68xvw0000gp/T/tmpevfl22c_/ to ~/.sky/.runtime_files/  [LogTimer=1201ms]
2023-01-17 19:54:55,056 INFO log_timer.py:25 -- NodeUpdater: ray-test-no-rsyc-image-head-5615c63a-compute: Applied config 71ac883b5dc808ecf144293dee29552141ba23da  [LogTimer=15733ms]
2023-01-17 19:55:01,483 ERR updater.py:159 -- New status: update-failed
2023-01-17 19:55:01,483 ERR updater.py:161 -- !!!
2023-01-17 19:55:01,483 VERR updater.py:169 -- {'message': 'SSH command failed.'}
2023-01-17 19:55:01,483 ERR updater.py:171 -- SSH command failed.
2023-01-17 19:55:01,483 ERR updater.py:173 -- !!!

I 01-17 19:55:02 cloud_vm_ray_backend.py:698] ====== stderr ======
Warning: Permanently added '34.72.143.188' (ED25519) to the list of known hosts.
Shared connection to 34.72.143.188 closed.
Shared connection to 34.72.143.188 closed.
bash: rsync: command not found
```

This seems to be a ray problem, as the file_mounts in the ray yaml requires the rsync to be installed on the remote cluster

**Comment by romilbhardwaj** [comment]
Same issue (rsync missing) when running SkyPilot inside a container `docker run -it --platform linux/amd64 --rm continuumio/miniconda3 /bin/bash`:

```
2023-03-20 18:24:44,043	INFO log_timer.py:25 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-077bda17f8dcdf868']  [LogTimer=203ms]
2023-03-20 18:24:44,045	ERR updater.py:158 -- New status: update-failed
2023-03-20 18:24:44,046	ERR updater.py:160 -- !!!
2023-03-20 18:24:44,046	VERR updater.py:168 -- {}
2023-03-20 18:24:44,047	ERR updater.py:170 -- [Errno 2] No such file or directory: 'rsync'
2023-03-20 18:24:44,047	ERR updater.py:172 -- !!!

I 03-20 18:24:44 cloud_vm_ray_backend.py:734] ====== stderr ======
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 153, in run
    self.do_update()
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 382, in do_update
    self.sync_file_mounts(self.rsync_up, step_numbers=(1, NUM_SETUP_STEPS))
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 242, in sync_file_mounts
    do_sync(remote_path, local_path)
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 229, in do_sync
    sync_cmd(local_path, remote_path, docker_mount_if_possible=True)
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/updater.py", line 535, in rsync_up
    self.cmd_runner.run_rsync_up(source, target, options=options)
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/command_runner.py", line 415, in run_rsync_up
    self._run_helper(command, silent=is_rsync_silent())
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/command_runner.py", line 272, in _run_helper
    return run_cmd_redirected(
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/subprocess_output_util.py", line 341, in run_cmd_redirected
    return _run_and_process_output(
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/subprocess_output_util.py", line 243, in _run_and_process_output
    return process_runner.check_call(
  File "/opt/conda/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rsync'
2023-03-20 18:24:44,275	PANIC commands.py:819 -- Failed to setup head node.
Traceback (most recent call last):
  File "/tmp/skypilot_ray_up_f5sgzku_.py", line 76, in <module>
    sdk.create_or_update_cluster('/root/.sky/generated/sky-b8c8-root.yml', **{'no_restart': True})
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 282, in create_or_update_cluster
    get_or_create_head_node(
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 819, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/opt/conda/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 610, in abort
    raise exc_cls(msg)
click.exceptions.ClickException: Failed to setup head node.
RuntimeError: Errors occurred during provision; check logs above.
```

**Comment by WoosukKwon** [comment]
The SCP developers reported the same issue: their CentOS image does not have rsync installed and thus failed to set up ray cluster. Can we provide a good workaround for this?

**Comment by Michaelvll** [comment]
@cblmemo is looking into this. He also met this problem when adding the docker support. Our workaround could be to override the CommandRunner of ray and install rsync if it does not exist.

**Comment by Michaelvll** [comment]
Another user encountered this issue, we should prioritize this issue a bit. @cblmemo Do you have time to take a look at this?

**Comment by cblmemo** [comment]
Sure, I'll take a look on it 🫡

**Comment by cblmemo** [comment]
After discussion, we decided to enable this feature through cloud-init, so IIUC this is blocked on the docker PR #1910 , which introduces cloud-init in Azure. I'll take a look at cloud-init in GCP first 🫡
