### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by lhqing** [skypilot-org/skypilot#1631]
Good morning sky team,

An `ModuleNotFoundError` after update skypilot yesterday.

```{shell}
$ sky status -r
Traceback (most recent call last):
  File "/Users/hanqingliu/mambaforge/bin/sky", line 5, in <module>
    from sky.cli import cli
  File "/Users/hanqingliu/mambaforge/lib/python3.9/site-packages/sky/__init__.py", line 10, in <module>
    from sky import backends
  File "/Users/hanqingliu/mambaforge/lib/python3.9/site-packages/sky/backends/__init__.py", line 3, in <module>
    from sky.backends.cloud_vm_ray_backend import CloudVmRayBackend
  File "/Users/hanqingliu/mambaforge/lib/python3.9/site-packages/sky/backends/cloud_vm_ray_backend.py", line 27, in <module>
    from sky import cloud_stores
  File "/Users/hanqingliu/mambaforge/lib/python3.9/site-packages/sky/cloud_stores.py", line 14, in <module>
    from sky.data import data_utils
  File "/Users/hanqingliu/mambaforge/lib/python3.9/site-packages/sky/data/__init__.py", line 2, in <module>
    from sky.data.storage import Storage, StorageMode, StoreType
  File "/Users/hanqingliu/mambaforge/lib/python3.9/site-packages/sky/data/storage.py", line 8, in <module>
    from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by Michaelvll** [comment]
Thank you for finding this! Could you try to run `pip install typing-extensions` to install that dependency?

**Comment by Michaelvll** [comment]
We just removed the dependency on the `typing_extensions`. It should work now if we update the SkyPilot to the latest master branch. Please feel free to let us know if any problems occur. : )

**Comment by lhqing** [comment]
@Michaelvll Sounds good. Yes, I was able to install that manually, just to let you know this missing dependency
