### ISSUE TITLE
[Lambda Cloud] Improve error message when there is no ip

### ISSUE THREAD

**Issue by ewzeng** [skypilot-org/skypilot#1678]
Running `sky launch --cloud lambda` followed immediately by `Ctrl-C` and `sky down -a` will yield:
```
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042] **** STDERR ****
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042] 2023-02-06 16:45:39,483  INFO util.py:335 -- setting max workers for head node type to 0
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042] 2023-02-06 16:45:39,660  INFO util.py:335 -- setting max workers for head node type to 0
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042] Traceback (most recent call last):
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/bin/ray", line 8, in <module>
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     sys.exit(main())
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2339, in main
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return cli()
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return self.main(*args, **kwargs)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1053, in main
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     rv = self.invoke(ctx)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return _process_result(sub_ctx.command.invoke(sub_ctx))
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return ctx.invoke(self.callback, **ctx.params)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/click/core.py", line 754, in invoke
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return __callback(*args, **kwargs)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return f(*args, **kwargs)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1224, in down
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     cluster_config_file, yes, workers_only, cluster_name, keep_min_workers
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 489, in teardown_cluster
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     A = remaining_nodes()
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/anaconda3/envs/sky/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 456, in remaining_nodes
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     head = provider.non_terminated_nodes({TAG_RAY_NODE_KIND: NODE_KIND_HEAD})
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/Desktop/ezeng/research/skypilot/sky/skylet/providers/lambda_cloud/node_provider.py", line 143, in non_terminated_nodes
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     nodes = self._get_filtered_nodes(tag_filters=tag_filters)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/Desktop/ezeng/research/skypilot/sky/skylet/providers/lambda_cloud/node_provider.py", line 33, in wrapper
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     return f(self, *args, **kwargs)
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/Desktop/ezeng/research/skypilot/sky/skylet/providers/lambda_cloud/node_provider.py", line 113, in _get_filtered_nodes
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     nodes = [self._extract_metadata(vm) for vm in filter(match_tags, vms)]
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/Desktop/ezeng/research/skypilot/sky/skylet/providers/lambda_cloud/node_provider.py", line 113, in <listcomp>
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     nodes = [self._extract_metadata(vm) for vm in filter(match_tags, vms)]
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]   File "/home/zeng/Desktop/ezeng/research/skypilot/sky/skylet/providers/lambda_cloud/node_provider.py", line 122, in _extract_metadata
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]     ip = vm['ip']
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042] KeyError: 'ip'
E 02-06 16:45:41 cloud_vm_ray_backend.py:3042]
```
This is because Lambda Cloud assigns ips after a cluster has booted. We should throw a error message to tell users to wait a few minutes before trying `sky down -a` again.

**Comment by ewzeng** [comment]
Another possible error (that runhouse gets) is:

![image](https://user-images.githubusercontent.com/46831164/224419968-cc4d28cd-dcfe-4878-971a-7842f4ad3382.png)
