### ISSUE TITLE
Error on setup: "No such file or directory: 'rsync'"

### ISSUE THREAD

**Issue by david-256** [skypilot-org/skypilot#1715]
When I create a GPU-VM with `sky gpunode --gpus A100`, an error occurs: `No such file or directory: 'rsync'`. The VM is created, but the setup does not seem to work.

Maybe the [provision log](https://github.com/skypilot-org/skypilot/files/10811870/provision.log.txt) is helpful to detect the error.

Shell input and output:
```sh
david@ml:/ml$ sky gpunode --gpus A100
I 02-23 09:36:31 optimizer.py:605] == Optimizer ==
I 02-23 09:36:31 optimizer.py:616] Target: minimizing cost
I 02-23 09:36:31 optimizer.py:628] Estimated cost: $1.1 / hour
I 02-23 09:36:31 optimizer.py:628] 
I 02-23 09:36:31 optimizer.py:691] Considered resources (1 node):
I 02-23 09:36:31 optimizer.py:739] --------------------------------------------------------------------------------------
I 02-23 09:36:31 optimizer.py:739]  CLOUD    INSTANCE           vCPUs   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 02-23 09:36:31 optimizer.py:739] --------------------------------------------------------------------------------------
I 02-23 09:36:31 optimizer.py:739]  Lambda   gpu_1x_a100_sxm4   30      A100:1         us-east-1     1.10          ✔     
I 02-23 09:36:31 optimizer.py:739]  GCP      a2-highgpu-1g      12      A100:1         us-central1   3.67                
I 02-23 09:36:31 optimizer.py:739] --------------------------------------------------------------------------------------
I 02-23 09:36:31 optimizer.py:739] 
I 02-23 09:36:31 optimizer.py:754] Multiple Lambda instances satisfy A100:1. The cheapest Lambda(gpu_1x_a100_sxm4, {'A100': 1}) is considered among:
I 02-23 09:36:31 optimizer.py:754] ['gpu_1x_a100_sxm4', 'gpu_1x_a100'].
I 02-23 09:36:31 optimizer.py:754] 
I 02-23 09:36:31 optimizer.py:760] To list more details, run 'sky show-gpus A100'.
Launching a new cluster 'sky-gpunode-david'. Proceed? [Y/n]: Y
Setting up interactive node sky-gpunode-david...
I 02-23 09:36:41 cloud_vm_ray_backend.py:3212] Creating a new cluster: "sky-gpunode-david" [1x Lambda(gpu_1x_a100_sxm4, {'A100': 1})].
I 02-23 09:36:41 cloud_vm_ray_backend.py:3212] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 02-23 09:36:41 cloud_vm_ray_backend.py:1124] To view detailed progress: tail -n100 -f /home/david/sky_logs/sky-2023-02-23-09-36-30-916833/provision.log
I 02-23 09:36:41 cloud_vm_ray_backend.py:1444] Launching on Lambda us-east-1 (all zones)
W 02-23 09:36:44 cloud_vm_ray_backend.py:804] Got error(s) in us-east-f1:
W 02-23 09:36:44 cloud_vm_ray_backend.py:806]   sky.skylet.providers.lambda_cloud.lambda_utils.LambdaCloudError: instance-operations/launch/insufficient-capacity: Not enough capacity to fulfill launch request. Regions with capacity available: us-west-2 asia-south-1
W 02-23 09:36:46 cloud_vm_ray_backend.py:1713] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1. Try changing resource requirements or use another region.
W 02-23 09:36:46 cloud_vm_ray_backend.py:1722] 
W 02-23 09:36:46 cloud_vm_ray_backend.py:1722] Provision failed for 1x Lambda(gpu_1x_a100_sxm4, {'A100': 1}) in us-east-1. Trying other locations (if any).
I 02-23 09:36:46 optimizer.py:605] == Optimizer ==
I 02-23 09:36:46 optimizer.py:616] Target: minimizing cost
I 02-23 09:36:46 optimizer.py:628] Estimated cost: $1.1 / hour
I 02-23 09:36:46 optimizer.py:628] 
I 02-23 09:36:46 optimizer.py:691] Considered resources (1 node):
I 02-23 09:36:46 optimizer.py:739] --------------------------------------------------------------------------------------
I 02-23 09:36:46 optimizer.py:739]  CLOUD    INSTANCE           vCPUs   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 02-23 09:36:46 optimizer.py:739] --------------------------------------------------------------------------------------
I 02-23 09:36:46 optimizer.py:739]  Lambda   gpu_1x_a100_sxm4   30      A100:1         us-west-2     1.10          ✔     
I 02-23 09:36:46 optimizer.py:739]  GCP      a2-highgpu-1g      12      A100:1         us-central1   3.67                
I 02-23 09:36:46 optimizer.py:739] --------------------------------------------------------------------------------------
I 02-23 09:36:46 optimizer.py:739] 
I 02-23 09:36:46 optimizer.py:754] Multiple Lambda instances satisfy A100:1. The cheapest Lambda(gpu_1x_a100_sxm4, {'A100': 1}) is considered among:
I 02-23 09:36:46 optimizer.py:754] ['gpu_1x_a100_sxm4', 'gpu_1x_a100'].
I 02-23 09:36:46 optimizer.py:754] 
I 02-23 09:36:46 optimizer.py:760] To list more details, run 'sky show-gpus A100'.
I 02-23 09:36:46 cloud_vm_ray_backend.py:1124] To view detailed progress: tail -n100 -f /home/david/sky_logs/sky-2023-02-23-09-36-30-916833/provision.log
I 02-23 09:36:47 cloud_vm_ray_backend.py:1444] Launching on Lambda us-west-2 (all zones)
I 02-23 09:38:51 log_utils.py:45] Head node is up.
I 02-23 09:38:54 cloud_vm_ray_backend.py:1493] Retrying runtime setup due to ssh connection issue.
I 02-23 09:38:54 cloud_vm_ray_backend.py:1514] Retrying launching in 3.7 seconds.
I 02-23 09:39:00 log_utils.py:45] Head node is up.
I 02-23 09:39:01 cloud_vm_ray_backend.py:1493] Retrying runtime setup due to ssh connection issue.
I 02-23 09:39:01 cloud_vm_ray_backend.py:1514] Retrying launching in 7.0 seconds.
I 02-23 09:39:13 log_utils.py:45] Head node is up.
I 02-23 09:39:14 cloud_vm_ray_backend.py:1493] Retrying runtime setup due to ssh connection issue.
I 02-23 09:39:14 cloud_vm_ray_backend.py:1514] Retrying launching in 7.3 seconds.
I 02-23 09:39:26 log_utils.py:45] Head node is up.
I 02-23 09:39:28 cloud_vm_ray_backend.py:1493] Retrying runtime setup due to ssh connection issue.
I 02-23 09:39:28 cloud_vm_ray_backend.py:1514] Retrying launching in 15.4 seconds.
I 02-23 09:39:48 log_utils.py:45] Head node is up.
I 02-23 09:39:50 cloud_vm_ray_backend.py:794] ====== stdout ======
 08:39:48 up 1 min,  1 user,  load average: 1.58, 0.60, 0.22
2023-02-23 09:39:44,143 INFO commands.py:276 -- Cluster: sky-gpunode-david
2023-02-23 09:39:44,144 VWARN commands.py:322 -- Loaded cached provider configuration from /tmp/ray-config-d8fe39cfa990e2623e74d6935399a9c3f4e0c5c8
2023-02-23 09:39:44,144 WARN commands.py:328 -- If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
2023-02-23 09:39:45,934 INFO commands.py:673 -- Cluster Ray runtime will not be restarted due to `--no-restart`.
2023-02-23 09:39:45,934 INFO commands.py:677 -- Updating cluster configuration and running setup commands. Confirm [y/N]: y [automatic, due to --yes]
2023-02-23 09:39:45,934 INFO commands.py:746 -- <1/1> Setting up head node
2023-02-23 09:39:45,935 INFO commands.py:767 -- Prepared bootstrap config
2023-02-23 09:39:46,407 INFO updater.py:324 -- New status: waiting-for-ssh
2023-02-23 09:39:46,408 INFO updater.py:261 -- [1/7] Waiting for SSH to become available
2023-02-23 09:39:46,408 INFO updater.py:266 -- Running `uptime` as a test.
2023-02-23 09:39:46,408 INFO command_runner.py:204 -- Fetched IP: 129.146.32.103
2023-02-23 09:39:46,408 INFO log_timer.py:25 -- NodeUpdater: c719a6881a254487b2d105dee84edc2c: Got IP  [LogTimer=0ms]
2023-02-23 09:39:46,408 VINFO command_runner.py:365 -- Running `uptime`
2023-02-23 09:39:46,408 VVINFO command_runner.py:367 -- Full command is `ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_172522ec10/0173051afe/%C -o ControlPersist=10s -o ConnectTimeout=5s ubuntu@129.146.32.103 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'`
2023-02-23 09:39:48,620 SUCC updater.py:280 -- Success.
2023-02-23 09:39:48,620 INFO log_timer.py:25 -- NodeUpdater: c719a6881a254487b2d105dee84edc2c: Got remote shell  [LogTimer=2213ms]
2023-02-23 09:39:48,620 INFO updater.py:374 -- Updating cluster configuration. [hash=c88a76e63d7c85200a45ae718b51abfaf3b2685b]
2023-02-23 09:39:49,092 INFO updater.py:381 -- New status: syncing-files
2023-02-23 09:39:49,092 INFO updater.py:238 -- [2/7] Processing file mounts
2023-02-23 09:39:49,092 VINFO command_runner.py:365 -- Running `mkdir -p ~/.sky/.runtime_files`
2023-02-23 09:39:49,092 VVINFO command_runner.py:367 -- Full command is `ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_172522ec10/0173051afe/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@129.146.32.103 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~/.sky/.runtime_files)'`
2023-02-23 09:39:49,443 VINFO command_runner.py:408 -- Running `rsync --rsh ssh -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_172522ec10/0173051afe/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz /tmp/tmp_8bvi_b5/ ubuntu@129.146.32.103:~/.sky/.runtime_files/`
2023-02-23 09:39:49,444 INFO log_timer.py:25 -- NodeUpdater: c719a6881a254487b2d105dee84edc2c: Synced /tmp/tmp_8bvi_b5/ to ~/.sky/.runtime_files/  [LogTimer=352ms]
2023-02-23 09:39:49,444 INFO log_timer.py:25 -- NodeUpdater: c719a6881a254487b2d105dee84edc2c: Applied config c88a76e63d7c85200a45ae718b51abfaf3b2685b  [LogTimer=3508ms]
2023-02-23 09:39:49,933 ERR updater.py:158 -- New status: update-failed
2023-02-23 09:39:49,933 ERR updater.py:160 -- !!!
2023-02-23 09:39:49,933 VERR updater.py:168 -- {}
2023-02-23 09:39:49,933 ERR updater.py:170 -- [Errno 2] No such file or directory: 'rsync'
2023-02-23 09:39:49,933 ERR updater.py:172 -- !!!

I 02-23 09:39:50 cloud_vm_ray_backend.py:797] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
Warning: Permanently added '129.146.32.103' (ED25519) to the list of known hosts.
Shared connection to 129.146.32.103 closed.
Shared connection to 129.146.32.103 closed.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/updater.py", line 153, in run
    self.do_update()
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/updater.py", line 382, in do_update
    self.sync_file_mounts(self.rsync_up, step_numbers=(1, NUM_SETUP_STEPS))
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/updater.py", line 242, in sync_file_mounts
    do_sync(remote_path, local_path)
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/updater.py", line 229, in do_sync
    sync_cmd(local_path, remote_path, docker_mount_if_possible=True)
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/updater.py", line 535, in rsync_up
    self.cmd_runner.run_rsync_up(source, target, options=options)
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/command_runner.py", line 409, in run_rsync_up
    self._run_helper(command, silent=is_rsync_silent())
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/command_runner.py", line 272, in _run_helper
    return run_cmd_redirected(
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/subprocess_output_util.py", line 341, in run_cmd_redirected
    return _run_and_process_output(
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/subprocess_output_util.py", line 243, in _run_and_process_output
    return process_runner.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rsync'
2023-02-23 09:39:50,396 PANIC commands.py:819 -- Failed to setup head node.
Traceback (most recent call last):
  File "/tmp/skypilot_ray_up_a3l7tx8w.py", line 42, in <module>
    sdk.create_or_update_cluster('/home/david/.sky/generated/sky-gpunode-david.yml', **{'no_restart': True})
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/commands.py", line 282, in create_or_update_cluster
    get_or_create_head_node(
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/commands.py", line 819, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/usr/local/lib/python3.10/dist-packages/ray/autoscaler/_private/cli_logger.py", line 610, in abort
    raise exc_cls(msg)
click.exceptions.ClickException: Failed to setup head node.
```

**Comment by Michaelvll** [comment]
Hi @david-kelm, thanks for reporting the issue! The problem seems to be caused by `rsync` is not installed on your local laptop. Could you install `rsync` and try again?
