### ISSUE TITLE
`sky queue` shows unnecessary error for auto-down cluster

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1753]
`sky queue` shows unnecessary ValueError for auto-down cluster.

To reproduce
```
> sky launch --cloud gcp --down -c test
(after a few mins)
> sky queue test
Fetching and parsing job queue...
Traceback (most recent call last):
  File "/opt/conda/envs/sky/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/sky/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/sky/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/gcpuser/sky_workdir/skypilot/sky/utils/common_utils.py", line 220, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/sky_workdir/skypilot/sky/cli.py", line 1024, in invoke
    return super().invoke(ctx)
  File "/opt/conda/envs/sky/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/sky/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/sky/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/gcpuser/sky_workdir/skypilot/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/sky_workdir/skypilot/sky/cli.py", line 1670, in queue
    job_table = core.queue(cluster, skip_finished, all_users)
  File "/home/gcpuser/sky_workdir/skypilot/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/sky_workdir/skypilot/sky/core.py", line 504, in queue
    handle = backend_utils.check_cluster_available(
  File "/home/gcpuser/sky_workdir/skypilot/sky/backends/backend_utils.py", line 2092, in check_cluster_available
    raise ValueError(
ValueError: Cluster 'test' does not exist.

(second time)
> sky queue test
Fetching and parsing job queue...
Cluster test not found.
```

 Instead, we should just show 
```
Fetching and parsing job queue...
Cluster test not found.
```
for the first `sky queue`?

**Comment by concretevitamin** [comment]
Fixed by #2389. Tested on 3213d3a1:
```
» sky queue test
Fetching and parsing job queue...
Failed to get the job queue for cluster 'test'.
  builtins.ValueError: Cluster 'test' not found on the cloud provider. It was either autodowned, or manually terminated in console.
```
