### ISSUE TITLE
Not able to launch any node

### ISSUE THREAD

**Issue by carloscdias** [skypilot-org/skypilot#1767]
I am getting the error below trying: launch, spot launch and even cpunode.

sky status report AWS, Azure and GCP enabled, but the error is the same in any cloud.

```bash
I 03-13 20:32:33 optimizer.py:605] == Optimizer ==
I 03-13 20:32:33 optimizer.py:617] Target: minimizing cost
I 03-13 20:32:33 optimizer.py:628] Estimated cost: $0.4 / hour
I 03-13 20:32:33 optimizer.py:628]
I 03-13 20:32:33 optimizer.py:692] Considered resources (1 node):
I 03-13 20:32:33 optimizer.py:739] -----------------------------------------------------------------------------------
I 03-13 20:32:33 optimizer.py:739]  CLOUD   INSTANCE         vCPUs   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 03-13 20:32:33 optimizer.py:739] -----------------------------------------------------------------------------------
I 03-13 20:32:33 optimizer.py:739]  AWS     m6i.2xlarge      8       -              us-east-1     0.38          ✔
I 03-13 20:32:33 optimizer.py:739]  Azure   Standard_D8_v5   8       -              eastus        0.38
I 03-13 20:32:33 optimizer.py:739]  GCP     n2-standard-8    8       -              us-central1   0.39
I 03-13 20:32:33 optimizer.py:739] -----------------------------------------------------------------------------------
I 03-13 20:32:33 optimizer.py:739]
Launching a new cluster 'sky-cpunode-carlos'. Proceed? [Y/n]:
Setting up interactive node sky-cpunode-carlos...
I 03-13 20:32:42 cloud_vm_ray_backend.py:3213] Creating a new cluster: "sky-cpunode-carlos" [1x AWS(m6i.2xlarge)].
I 03-13 20:32:42 cloud_vm_ray_backend.py:3213] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 03-13 20:32:43 cloud_vm_ray_backend.py:1124] To view detailed progress: tail -n100 -f /Users/carlos/sky_logs/sky-2023-03-13-20-32-32-696310/provision.log
I 03-13 20:32:44 cloud_vm_ray_backend.py:1444] Launching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1f)
I 03-13 20:34:16 log_utils.py:45] Head node is up.
I 03-13 20:36:01 cloud_vm_ray_backend.py:1256] Successfully provisioned or found existing VM.
Clusters
NAME                LAUNCHED    RESOURCES            STATUS  AUTOSTOP  COMMAND
sky-cpunode-carlos  3 mins ago  1x AWS(m6i.2xlarge)  INIT    -         sky cpunode

Traceback (most recent call last):
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11232aad0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='8.8.8.8', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11232aad0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlos/.pyenv/versions/skypilot/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 220, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/cli.py", line 1010, in invoke
    return super().invoke(ctx)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/cli.py", line 2591, in cpunode
    retry_until_up=retry_until_up,
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/cli.py", line 835, in _create_and_ssh_into_node
    node_type=node_type,
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/cli.py", line 755, in _launch_with_confirm
    no_setup=no_setup,
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/execution.py", line 418, in launch
    _is_launched_by_spot_controller=_is_launched_by_spot_controller,
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/execution.py", line 272, in _execute
    retry_until_up=retry_until_up)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 220, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/backends/backend.py", line 50, in provision
    cluster_name, retry_until_up)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2195, in _provision
    use_cached_ips=False)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/backends/cloud_vm_ray_backend.py", line 1943, in external_ips
    self._update_stable_cluster_ips(max_attempts=max_attempts)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/backends/cloud_vm_ray_backend.py", line 1888, in _update_stable_cluster_ips
    get_internal_ips=False)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/backends/backend_utils.py", line 1290, in get_node_ips
    check_network_connection()
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/sky/backends/backend_utils.py", line 1535, in check_network_connection
    http.head(_TEST_IP, timeout=3)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/requests/sessions.py", line 622, in head
    return self.request("HEAD", url, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/carlos/.pyenv/versions/3.7/envs/skypilot/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='8.8.8.8', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11232aad0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

Any suggestions?

**Comment by concretevitamin** [comment]
Thanks for the report @carloscdias. 

It appears 

https://github.com/skypilot-org/skypilot/blob/77e6f31be4be232845e270a30a9c8b5702d0a1c4/sky/backends/backend_utils.py#L1332

is failing due to the test IP `8.8.8.8` cannot be reached. 

Could you  try commenting out the line above (this works assuming you have installed from the master branch via `pip install -e ...`)? 

We should look into an alternative method in testing network connectivity.

**Comment by carloscdias** [comment]
It worked! Thanks!
