### ISSUE TITLE
Deal gracefully with missing credentials

### ISSUE THREAD

**Issue by eli-osherovich** [skypilot-org/skypilot#1769]
We currently use only Azure, hence, no credentials for GCP or AWS. Some commands fail due to this. 

Fro example, running `sky show-gpus A100` generate the following error:

```
(py38) ➜  sky sky show-gpus A100
I 03-14 11:50:15 aws_catalog.py:53] Fetching availability zones mapping for AWS...
Traceback (most recent call last):
  File "/Users/eli/virtenvs/py38/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/utils/common_utils.py", line 220, in _record
    return f(*args, **kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/cli.py", line 1010, in invoke
    return super().invoke(ctx)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/utils/common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/cli.py", line 2736, in show_gpus
    service_catalog.validate_region_zone(region, None, clouds=cloud)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/clouds/service_catalog/__init__.py", line 110, in validate_region_zone
    return _map_clouds_catalog(clouds, 'validate_region_zone', region_name,
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/clouds/service_catalog/__init__.py", line 31, in _map_clouds_catalog
    cloud_module = importlib.import_module(
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/clouds/service_catalog/aws_catalog.py", line 70, in <module>
    _df = _apply_az_mapping(_df)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/clouds/service_catalog/aws_catalog.py", line 57, in _apply_az_mapping
    az_mappings = fetch_aws.fetch_availability_zone_mappings()
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/clouds/service_catalog/data_fetchers/fetch_aws.py", line 336, in fetch_availability_zone_mappings
    regions = list(get_enabled_regions())
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/sky/clouds/service_catalog/data_fetchers/fetch_aws.py", line 69, in get_enabled_regions
    user_cloud_regions = aws_client.describe_regions()['Regions']
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/Users/eli/virtenvs/py38/lib/python3.8/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by concretevitamin** [comment]
Thanks for the report. This has been fixed in master [recently](https://github.com/skypilot-org/skypilot/commit/f3caa1710ab96025ef187d522590894a3a63acc5). (We really should cut patch releases more frequently!)

In the meantime, could you try installing from source?
```bash
pip install git+https://github.com/skypilot-org/skypilot.git#egg=skypilot[azure]
```

**Comment by eli-osherovich** [comment]
I can confirm that the issue is solved.
