### ISSUE TITLE
Provision failed when using custom image on GCP

### ISSUE THREAD

**Issue by lhqing** [skypilot-org/skypilot#1923]
Hi SkyPilot team,

**Problem:**
When use custom image to start VM, the provision will fail if some essential softwares are missing, for example `rsync`. 

**Reproduce:**
Create a VM with base Debian10 image on GCP, where `rsync` is not installed by default
```{yaml}
resources:
  cloud: gcp
  instance_type: n2d-standard-32
  region: us-west1
  disk_size: 256
  image_id: basic-debian10-image
```

**Solution:**
I can solve this problem by install `rsync` manually or in the image. My understanding is I can not do this in `setup` because the error happens before setup section.

**Log:**
Before install rsync:
```
sky launch -c jupyter -y sky-jupyter.yaml
Task from YAML spec: sky-jupyter.yaml
W 05-01 17:04:42 resources.py:860] image_id in resources is experimental. It only supports AWS/GCP.
I 05-01 17:04:45 optimizer.py:617] == Optimizer ==
I 05-01 17:04:45 optimizer.py:640] Estimated cost: $1.4 / hour
I 05-01 17:04:45 optimizer.py:640] 
I 05-01 17:04:45 optimizer.py:712] Considered resources (1 node):
I 05-01 17:04:45 optimizer.py:760] ----------------------------------------------------------------------------------------------
I 05-01 17:04:45 optimizer.py:760]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 05-01 17:04:45 optimizer.py:760] ----------------------------------------------------------------------------------------------
I 05-01 17:04:45 optimizer.py:760]  GCP     n2d-standard-32   32      128       -              us-west1      1.35          ✔     
I 05-01 17:04:45 optimizer.py:760] ----------------------------------------------------------------------------------------------
I 05-01 17:04:45 optimizer.py:760] 
Running task on cluster jupyter...
I 05-01 17:04:45 cloud_vm_ray_backend.py:3327] Creating a new cluster: "jupyter" [1x GCP(n2d-standard-32, image_id={'us-west1': 'projects/prod-635e/global/images/hanqing-base-debian10'})].
I 05-01 17:04:45 cloud_vm_ray_backend.py:3327] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 05-01 17:04:46 cloud_vm_ray_backend.py:1156] To view detailed progress: tail -n100 -f /Users/hanqingliu/sky_logs/sky-2023-05-01-17-04-44-387406/provision.log
I 05-01 17:04:48 authentication.py:199] OS Login is enabled for GCP project prod-635e. Running additional authentication steps.
I 05-01 17:04:52 cloud_vm_ray_backend.py:1480] Launching on GCP us-west1 (us-west1-a)
I 05-01 17:05:43 log_utils.py:89] Head node is up.
I 05-01 17:05:57 cloud_vm_ray_backend.py:1529] Retrying runtime setup due to ssh connection issue.
I 05-01 17:05:57 cloud_vm_ray_backend.py:1550] Retrying launching in 3.2 seconds.
I 05-01 17:06:11 log_utils.py:89] Head node is up.
I 05-01 17:06:25 cloud_vm_ray_backend.py:1529] Retrying runtime setup due to ssh connection issue.
I 05-01 17:06:25 cloud_vm_ray_backend.py:1550] Retrying launching in 5.9 seconds.
I 05-01 17:06:41 log_utils.py:89] Head node is up.
I 05-01 17:06:55 cloud_vm_ray_backend.py:1529] Retrying runtime setup due to ssh connection issue.
I 05-01 17:06:55 cloud_vm_ray_backend.py:1550] Retrying launching in 9.6 seconds.
I 05-01 17:07:16 log_utils.py:89] Head node is up.
I 05-01 17:07:29 cloud_vm_ray_backend.py:1529] Retrying runtime setup due to ssh connection issue.
I 05-01 17:07:29 cloud_vm_ray_backend.py:1550] Retrying launching in 20.0 seconds.
I 05-01 17:08:01 log_utils.py:89] Head node is up.
I 05-01 17:08:14 cloud_vm_ray_backend.py:687] ====== stdout ======
2023-05-01 17:07:50,226 INFO commands.py:276 -- Cluster: jupyter
2023-05-01 17:07:50,227 VWARN commands.py:322 -- Loaded cached provider configuration from /var/folders/fv/88lmpgd95tb8kf5x2n31_d5m0000gn/T/ray-config-e3df3a1a7832158b33807db9cd4c7b34275ecce6
2023-05-01 17:07:50,227 WARN commands.py:328 -- If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
2023-05-01 17:07:53,474 INFO commands.py:673 -- Cluster Ray runtime will not be restarted due to `--no-restart`.
2023-05-01 17:07:53,475 INFO commands.py:677 -- Updating cluster configuration and running setup commands. Confirm [y/N]: y [automatic, due to --yes]
Skipped creating a new head node.
2023-05-01 17:07:53,476 INFO commands.py:746 -- <1/1> Setting up head node
2023-05-01 17:07:53,480 INFO commands.py:767 -- Prepared bootstrap config
I 05-01 17:07:53 node.py:343] wait_for_compute_zone_operation: Waiting for operation operation-1682986073795-5faaabb172c1c-9a828d88-e8e874ec to finish...
I 05-01 17:07:59 node.py:362] wait_for_compute_zone_operation: Operation operation-1682986073795-5faaabb172c1c-9a828d88-e8e874ec finished.
 00:08:01 up 2 min,  1 user,  load average: 0.16, 0.09, 0.03
2023-05-01 17:07:59,538 INFO updater.py:324 -- New status: waiting-for-ssh
2023-05-01 17:07:59,538 INFO updater.py:261 -- [1/7] Waiting for SSH to become available
2023-05-01 17:07:59,538 INFO updater.py:266 -- Running `uptime` as a test.
2023-05-01 17:07:59,538 INFO command_runner.py:204 -- Fetched IP: 35.247.3.109
2023-05-01 17:07:59,538 INFO log_timer.py:25 -- NodeUpdater: ray-jupyter-head-520f1e05-compute: Got IP  [LogTimer=0ms]
2023-05-01 17:07:59,539 VINFO command_runner.py:371 -- Running `uptime`
2023-05-01 17:07:59,539 VVINFO command_runner.py:373 -- Full command is `ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_a51332a570/9f3bc30808/%C -o ControlPersist=10s -o ConnectTimeout=10s hanliu_salk_edu@35.247.3.109 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'`
2023-05-01 17:08:01,807 SUCC updater.py:280 -- Success.
2023-05-01 17:08:01,808 INFO log_timer.py:25 -- NodeUpdater: ray-jupyter-head-520f1e05-compute: Got remote shell  [LogTimer=2270ms]
2023-05-01 17:08:01,808 INFO updater.py:374 -- Updating cluster configuration. [hash=eb471c4455948f94325fdb9bb95391697454aa95]
I 05-01 17:08:02 node.py:343] wait_for_compute_zone_operation: Waiting for operation operation-1682986082292-5faaabb98d270-17a0fab8-b3a91269 to finish...
I 05-01 17:08:07 node.py:362] wait_for_compute_zone_operation: Operation operation-1682986082292-5faaabb98d270-17a0fab8-b3a91269 finished.
2023-05-01 17:08:07,701 INFO updater.py:381 -- New status: syncing-files
2023-05-01 17:08:07,701 INFO updater.py:238 -- [2/7] Processing file mounts
2023-05-01 17:08:07,701 VINFO command_runner.py:371 -- Running `mkdir -p ~/.sky/.runtime_files`
2023-05-01 17:08:07,701 VVINFO command_runner.py:373 -- Full command is `ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_a51332a570/9f3bc30808/%C -o ControlPersist=10s -o ConnectTimeout=120s hanliu_salk_edu@35.247.3.109 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~/.sky/.runtime_files)'`
2023-05-01 17:08:08,650 VINFO command_runner.py:414 -- Running `rsync --rsh ssh -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_a51332a570/9f3bc30808/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz /var/folders/fv/88lmpgd95tb8kf5x2n31_d5m0000gn/T/tmp62jlxc2o/ hanliu_salk_edu@35.247.3.109:~/.sky/.runtime_files/`
2023-05-01 17:08:08,735 INFO log_timer.py:25 -- NodeUpdater: ray-jupyter-head-520f1e05-compute: Synced /var/folders/fv/88lmpgd95tb8kf5x2n31_d5m0000gn/T/tmp62jlxc2o/ to ~/.sky/.runtime_files/  [LogTimer=1034ms]
2023-05-01 17:08:08,735 INFO log_timer.py:25 -- NodeUpdater: ray-jupyter-head-520f1e05-compute: Applied config eb471c4455948f94325fdb9bb95391697454aa95  [LogTimer=15255ms]
I 05-01 17:08:09 node.py:343] wait_for_compute_zone_operation: Waiting for operation operation-1682986089180-5faaabc01ec3c-48bcf662-85bb22eb to finish...
I 05-01 17:08:14 node.py:362] wait_for_compute_zone_operation: Operation operation-1682986089180-5faaabc01ec3c-48bcf662-85bb22eb finished.
2023-05-01 17:08:14,633 ERR updater.py:158 -- New status: update-failed
2023-05-01 17:08:14,633 ERR updater.py:160 -- !!!
2023-05-01 17:08:14,633 VERR updater.py:168 -- {'message': 'SSH command failed.'}
2023-05-01 17:08:14,633 ERR updater.py:170 -- SSH command failed.
2023-05-01 17:08:14,633 ERR updater.py:172 -- !!!

I 05-01 17:08:14 cloud_vm_ray_backend.py:690] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
Warning: Permanently added '35.247.3.109' (ED25519) to the list of known hosts.
Shared connection to 35.247.3.109 closed.
Shared connection to 35.247.3.109 closed.
bash: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: remote command not found (code 127) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/io.c(453) [sender=2.6.9]
2023-05-01 17:08:14,744 PANIC commands.py:819 -- Failed to setup head node.
Traceback (most recent call last):
  File "/var/folders/fv/88lmpgd95tb8kf5x2n31_d5m0000gn/T/skypilot_ray_up_4h6h3_0s.py", line 76, in <module>
    sdk.create_or_update_cluster('/Users/hanqingliu/.sky/generated/jupyter.yml', **{'no_restart': True})
  File "/Users/hanqingliu/mambaforge/lib/python3.10/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/Users/hanqingliu/mambaforge/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 282, in create_or_update_cluster
    get_or_create_head_node(
  File "/Users/hanqingliu/mambaforge/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 819, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/Users/hanqingliu/mambaforge/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 610, in abort
    raise exc_cls(msg)
click.exceptions.ClickException: Failed to setup head node.
```

Manually check the error command:
```
(base) hanliu_salk_edu@ray-jupyter-head-520f1e05-compute:~/.sky/.runtime_files$ rsync --rsh ssh -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_a51332a570/9f3bc30808/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz /var/folders/fv/88lmpgd95tb8kf5x2n31_d5m0000gn/T/tmp62jlxc2o/ hanliu_salk_edu@35.247.3.109:~/.sky/.runtime_files/
-bash: rsync: command not found
```

**Comment by Michaelvll** [comment]
Thanks for reporting this issue @lhqing! Yes, that is a long-existing problem that `ray up` requires `rsync` to be pre-installed on the image. 

Note to ourselves: We can consider using `cloud-init` to ensure the existence of `rsync`, but the debian images do not support cloud-init.
