### ISSUE TITLE
sky launch hangs on azure

### ISSUE THREAD

**Issue by kyteague** [skypilot-org/skypilot#2008]
I tried to the hello world example command: `sky launch 'echo Hello, SkyPilot!'`

And get the following error
```
➜  ~ sky launch 'echo Hello, SkyPilot!'
Task from command: echo Hello, SkyPilot!
I 06-01 18:21:46 optimizer.py:636] == Optimizer ==
I 06-01 18:21:46 optimizer.py:647] Target: minimizing cost
I 06-01 18:21:46 optimizer.py:659] Estimated cost: $0.4 / hour
I 06-01 18:21:46 optimizer.py:659]
I 06-01 18:21:46 optimizer.py:732] Considered resources (1 node):
I 06-01 18:21:46 optimizer.py:781] ----------------------------------------------------------------------------------------------
I 06-01 18:21:46 optimizer.py:781]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 06-01 18:21:46 optimizer.py:781] ----------------------------------------------------------------------------------------------
I 06-01 18:21:46 optimizer.py:781]  Azure   Standard_D8s_v5   8       32        -              eastus        0.38          ✔
I 06-01 18:21:46 optimizer.py:781] ----------------------------------------------------------------------------------------------
I 06-01 18:21:46 optimizer.py:781]
Launching a new cluster 'sky-571e-kyle'. Proceed? [Y/n]: Y
I 06-01 18:22:05 cloud_vm_ray_backend.py:3492] Creating a new cluster: "sky-571e-kyle" [1x Azure(Standard_D8s_v5)].
I 06-01 18:22:05 cloud_vm_ray_backend.py:3492] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 06-01 18:22:06 cloud_vm_ray_backend.py:1215] To view detailed progress: tail -n100 -f /Users/kyle/sky_logs/sky-2023-06-01-18-16-45-477620/provision.log
I 06-01 18:22:06 cloud_vm_ray_backend.py:1539] Launching on Azure eastus
I 06-01 18:22:37 cloud_vm_ray_backend.py:1567] Retrying head node provisioning due to Azure CLI issues.
I 06-01 18:22:37 cloud_vm_ray_backend.py:1621] Retrying launching in 6.0 seconds.
I 06-01 18:23:14 cloud_vm_ray_backend.py:1567] Retrying head node provisioning due to Azure CLI issues.
I 06-01 18:23:14 cloud_vm_ray_backend.py:1621] Retrying launching in 6.1 seconds.
I 06-01 18:23:51 cloud_vm_ray_backend.py:1567] Retrying head node provisioning due to Azure CLI issues.
I 06-01 18:23:51 cloud_vm_ray_backend.py:1621] Retrying launching in 6.1 seconds.
I 06-01 18:24:28 cloud_vm_ray_backend.py:1567] Retrying head node provisioning due to Azure CLI issues.
I 06-01 18:24:28 cloud_vm_ray_backend.py:1621] Retrying launching in 6.7 seconds.
I 06-01 18:25:06 cloud_vm_ray_backend.py:804] ====== stdout ======
2023-06-01 18:24:35,487	INFO commands.py:276 -- Cluster: sky-571e-kyle
2023-06-01 18:24:35,886	INFO commands.py:353 -- Checking External environment settings
I 06-01 18:24:35 config.py:57] Using subscription id: a31a6a99-e12e-4354-bfb2-d2a2ac105bc1
I 06-01 18:24:35 config.py:72] Creating/Updating resource group: sky-571e-kyle-eastus

I 06-01 18:25:06 cloud_vm_ray_backend.py:807] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
AzureCliCredential.get_token failed: Failed to invoke the Azure CLI
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/azure/identity/_credentials/azure_cli.py", line 169, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 2022, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1198, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource https://management.azure.com']' timed out after 30 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/2g/tp0wnt4905sfnyz0dzjkmmhm0000gn/T/skypilot_ray_up_n28359ed.py", line 76, in <module>
    sdk.create_or_update_cluster('/Users/kyle/.sky/generated/sky-571e-kyle.yml', **{'no_restart': True})
  File "/opt/homebrew/lib/python3.10/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/opt/homebrew/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 279, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/opt/homebrew/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 381, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/opt/homebrew/lib/python3.10/site-packages/sky/skylet/providers/azure/node_provider.py", line 421, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/opt/homebrew/lib/python3.10/site-packages/sky/skylet/providers/azure/config.py", line 40, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/opt/homebrew/lib/python3.10/site-packages/sky/skylet/providers/azure/config.py", line 76, in _configure_resource_group
    rg_create_or_update(resource_group_name=resource_group, parameters=params)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 11417, in create_or_update
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/homebrew/lib/python3.10/site-packages/azure/mgmt/core/policies/_base.py", line 46, in send
    response = self.next.send(request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send
    response = self.next.send(request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 448, in send
    response = self.next.send(request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 108, in send
    self.on_request(request)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 87, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/identity/_credentials/azure_cli.py", line 99, in get_token
    output = _run_command(command, self._process_timeout)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/identity/_credentials/azure_cli.py", line 191, in _run_command
    six.raise_from(error, ex)
  File "<string>", line 3, in raise_from
azure.identity._exceptions.CredentialUnavailableError: Failed to invoke the Azure CLI
```

It seems to be because of this command hanging (confirmed manually running myself)
```
az account get-access-token --output json --resource https://management.azure.com
```

If I remove the `--resource` part the command works fine.

Versions
```
➜  ~ az version
{
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
➜  ~ sky --version
skypilot, version 0.3.0
```

**Comment by kyteague** [comment]
I disabled ipv6 on my machine and the command now works. I think it's a problem with my local ISP (Vivo) in Brazil. Very strange! Perhaps the `az` command wants trying to connect to `management.azure.com` using ipv6.
