### ISSUE TITLE
[OCI] `sky show-gpus` is broken if OCI is not installed

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2094]
Running `sky show-gpus` on a machine without OCI installed:
```
(base) root@ae8df2700134:/skypilot# sky show-gpus
Traceback (most recent call last):
  File "/opt/conda/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/skypilot/sky/utils/common_utils.py", line 235, in _record
    return f(*args, **kwargs)
  File "/skypilot/sky/cli.py", line 1090, in invoke
    return super().invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/skypilot/sky/clouds/service_catalog/config.py", line 46, in wrapper
    return func(*args, **kwargs)
  File "/skypilot/sky/utils/common_utils.py", line 256, in _record
    return f(*args, **kwargs)
  File "/skypilot/sky/cli.py", line 3050, in show_gpus
    service_catalog.validate_region_zone(region, None, clouds=cloud)
  File "/skypilot/sky/clouds/service_catalog/__init__.py", line 119, in validate_region_zone
    return _map_clouds_catalog(clouds, 'validate_region_zone', region_name,
  File "/skypilot/sky/clouds/service_catalog/__init__.py", line 44, in _map_clouds_catalog
    results.append(method(*args, **kwargs))
  File "/skypilot/sky/clouds/service_catalog/oci_catalog.py", line 81, in validate_region_zone
    return common.validate_region_zone_impl('oci', _get_df(), region, zone)
  File "/skypilot/sky/clouds/service_catalog/oci_catalog.py", line 48, in _get_df
    except (oci_adaptor.get_oci().exceptions.ConfigFileNotFound,
  File "/skypilot/sky/adaptors/oci.py", line 23, in wrapper
    raise ImportError('Fail to import dependencies for OCI.'
ImportError: Fail to import dependencies for OCI.Try pip install "skypilot[oci]"
```

Likely culprit is _get_df in `oci_catalog.py`, which requires the `oci` packages to be installed.

**Comment by concretevitamin** [comment]
cc @HysunHe 

On a docker installing 0.3.1, this problem did not occur; likely affecting the master branch only.

**Comment by HysunHe** [comment]
> cc @HysunHe
> 
> On a docker installing 0.3.1, this problem did not occur; likely affecting the master branch only.

Yes, that's a defect introduced by the #2047. I missed the "ImportError" when OCI is not installed. Thanks @Michaelvll for the fix.
