### ISSUE TITLE
[Ray / Spot] autoscaler failed during spot cancel

### ISSUE THREAD

**Issue by MaoZiming** [skypilot-org/skypilot#2150]
The error can be reproduced on the `master` branch
```
2023-06-29 12:56:56,041 WARNING worker.py:2000 -- The autoscaler failed with the following error:
Terminated with signal 15
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 674, in <module>
    monitor.run()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 550, in run
    self._run()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 454, in _run
    time.sleep(AUTOSCALER_UPDATE_INTERVAL_S)

Traceback (most recent call last):
  File "/home/gcpuser/.sky/sky_app/sky_job_1", line 488, in <module>
    returncodes = ray.get(futures)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/worker.py", line 2537, in get
    raise value
ray.exceptions.LocalRayletDiedError: The task's local raylet died. Check raylet.out for more information.
Shared connection to 34.130.169.19 closed.
I 06-29 12:56:58 spot_utils.py:381] Logs finished for job 1 (status: CANCELLING).
```

To reproduce the error, run
```
sky spot launch example.yaml
sky down cluster # when the cluster is still UP
sky spot cancel -a
```
The example.yaml is quite simple:
```
resources:
  cloud: gcp

setup: |
  echo "Running setup."

run: |
  echo "Hello, SkyPilot!"
  conda env list
  sleep 600
```

**Comment by Michaelvll** [comment]
It seems the warning is harmless for the spot jobs but confusing. Maybe we should check if there is a way to disable the warning or just do the postprocessing for the logging
