### ISSUE TITLE
assertion errors when launching with multiple resources

### ISSUE THREAD

**Issue by ErwannMillon** [skypilot-org/skypilot#2333]
Hey there, 

I'm getting this error when launching a skypilot task with a set of multiple resources with 

```
resources = [Resources(cloud=sky.clouds.Lambda(), accelerators="A10:1"), Resources(cloud=sky.clouds.Lambda(), accelerators="A6000:1"), Resources(cloud=sky.clouds.Lambda(), accelerators="A100:1")]
skypilot_task.set_resources(resources)
skypilot_task.set_time_estimator(time_estimator)
```

```
Traceback (most recent call last):
File "skypilot_utils.py", line 156, in <module>
test()
File "skypilot_utils.py", line 141, in test
x = sky.launch(
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/utils/common_utils.py", line 260, in _record
return f(*args, **kwargs)
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/utils/common_utils.py", line 260, in _record
return f(*args, **kwargs)
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/execution.py", line 487, in launch
_execute(
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/execution.py", line 324, in _execute
handle = backend.provision(task,
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/utils/common_utils.py", line 260, in _record
return f(*args, **kwargs)
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/utils/common_utils.py", line 239, in _record
return f(*args, **kwargs)
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/backends/backend.py", line 55, in provision
usage_lib.messages.usage.update_actual_task(task)
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/usage/usage_lib.py", line 171, in update_actual_task
self.actual_task = prepare_json_from_yaml_config(task.to_yaml_config())
File "/opt/conda/envs/gen5/lib/python3.8/site-packages/sky/task.py", line 881, in to_yaml_config
assert len(self.resources) == 1
AssertionError
```

I know that support is experimental, is this normal ?
Best,
Erwann :)

**Comment by concretevitamin** [comment]
Hey Erwann - `Task.set_resources()` should take either a Resources, or a Set of Resources ([docs](https://skypilot.readthedocs.io/en/latest/reference/api.html#task)). The latter case is EXPERIMENTAL and indicates asking the optimizer to “pick the best of these resources” to run this task.

Curious what's your use case. By passing a list, did you mean to say "pick the cheapest of these that is available", or "try these resources in the given order", or...?

**Comment by ErwannMillon** [comment]
Hi,
I'm indeed trying to provision a single node, and to try to iterate through my list of Resources in order until one is successfully provisioned. 

Either just always try each resource in the list of Resources in every iteration of the retry_until_up loop in skypilot/sky/backends/cloud_vm_ray_backend.py , or perhaps try each until a user-inputted threshold of `attempts_cnt` / `gap_seconds` .

**Comment by concretevitamin** [comment]
Related: #1361

**Comment by Michaelvll** [comment]
Hi @ErwannMillon, this feature has been recently added by #1389. Please feel free to try it out by refering to https://skypilot.readthedocs.io/en/latest/examples/auto-failover.html#multiple-candidate-gpus
Closing this issue for now.
