### ISSUE TITLE
[K8s] Handle exceptions and pod leakage for evicted containers 

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2357]
I was running a job which got OOM killed by Kubernetes (`OOMKilled` can be due to namespace memory limits etc.). When I ran `sky exec`, I got a cryptic error:

```
(base) ➜  examples git:(k8s_cloud_gpu) ✗ sky exec resnet resnet_app.yaml
Task from YAML spec: resnet_app.yaml
Executing task on cluster resnet...
I 08-07 09:03:46 cloud_vm_ray_backend.py:3186] 
I 08-07 09:03:46 cloud_vm_ray_backend.py:3186] Cluster name: resnet
I 08-07 09:03:46 cloud_vm_ray_backend.py:3186] To log into the head VM: ssh resnet
I 08-07 09:03:46 cloud_vm_ray_backend.py:3186] To submit a job:         sky exec resnet yaml_file
I 08-07 09:03:46 cloud_vm_ray_backend.py:3186] To stop the cluster:     sky stop resnet
I 08-07 09:03:46 cloud_vm_ray_backend.py:3186] To teardown the cluster: sky down resnet
Clusters
NAME    LAUNCHED    RESOURCES                                     STATUS  AUTOSTOP  COMMAND                       
resnet  5 mins ago  1x Kubernetes(2CPU--2GB--1K80, {'K80': 1.0})  UP      -         sky exec resnet resnet_ap...  
aec     19 hrs ago  1x GCP(n2-standard-8)                         UP      -         sky launch -c aec --cloud...  

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 468, in websocket_call
    client = WSClient(configuration, url, headers, capture_all)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 62, in __init__
    self.sock = create_websocket(configuration, url, headers)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 452, in create_websocket
    websocket.connect(url, header=header)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/websocket/_handshake.py", line 148, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status {status} {message} -+-+- {headers} -+-+- {body}".format(status=status, message=status_message, headers=resp_headers, body=response_body), status, status_message, resp_headers, response_body)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error -+-+- {'content-length': '32', 'content-type': 'text/plain; charset=utf-8', 'date': 'Mon, 07 Aug 2023 03:33:46 GMT'} -+-+- b'container not found ("ray-node")'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 250, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 1132, in invoke
    return super().invoke(ctx)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 271, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 1548, in exec
    sky.exec(task, backend=backend, cluster_name=cluster, detach_run=detach_run)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 271, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/execution.py", line 575, in exec
    _execute(entrypoint=entrypoint,
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/execution.py", line 358, in _execute
    backend.execute(handle, task, detach_run, dryrun=dryrun)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 271, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 250, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/backend.py", line 93, in execute
    return self._execute(handle, task, detach_run, dryrun)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/cloud_vm_ray_backend.py", line 3156, in _execute
    self._update_envs_for_k8s(handle, task)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/cloud_vm_ray_backend.py", line 2830, in _update_envs_for_k8s
    cloud_env_vars = handle.launched_resources.cloud.query_env_vars(
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/clouds/kubernetes.py", line 512, in query_env_vars
    response = kubernetes.stream()(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
    return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info
    return self.api_client.call_api(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 474, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: Handshake status 500 Internal Server Error -+-+- {'content-length': '32', 'content-type': 'text/plain; charset=utf-8', 'date': 'Mon, 07 Aug 2023 03:33:46 GMT'} -+-+- b'container not found ("ray-node")'
```

When I ran `sky status -r`, the sky cluster got removed from my status table even though the pod still existed:
```
(base) ➜  ~ sky status -r
Clusters
Refreshing status for 2 clusters ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
W 08-07 09:27:13 backend_utils.py:2475] Cluster terminated on the cloud: resnet
NAME  LAUNCHED    RESOURCES              STATUS  AUTOSTOP  COMMAND
aec   20 hrs ago  1x GCP(n2-standard-8)  UP      -         sky launch -c aec --cloud...

Managed spot jobs
No in progress jobs. (See: sky spot -h)
(base) ➜  ~ sky status
Clusters
NAME  LAUNCHED    RESOURCES              STATUS  AUTOSTOP  COMMAND
aec   20 hrs ago  1x GCP(n2-standard-8)  UP      -         sky launch -c aec --cloud...

Managed spot jobs
No in progress jobs. (See: sky spot -h)

# Pod still exists:
(base) ➜  ~ k get pods
NAME              READY   STATUS      RESTARTS   AGE
resnet-ray-head   0/1     OOMKilled   0          29m
```

We should handle these failures gracefully and update sky status table correctly by terminating the associated pod too.

**Comment by aviweit** [comment]
@romilbhardwaj ,

I looked into it and it seems that I was able to replicate it on our local environment.

1. `sky launch -c test -- echo hi`
2. wait for task to complete
3. `sky exec test -- echo hi1` completes successfully
4. login to ray pod: `ssh test`
5. emulate OOM: kill process "sleep infinity" (e.g. `kill -9 13`). Main container is terminated
6. `sky exec test -- echo hi1` prints similar error stack (`-+-+- b'container not found ("ray-node")`)
7. `sky status -r` removes the cluster from local db
8. ray pod and service still exist in k8s cluster
9. `sky down test` did not help

I would like to comment:

* After step (6) when running sky status -- the status reported is: `UP` although the ray pod was not in `Running` state.
  I think that it needs to be set to `INIT` or other value rather than `UP`, to denote that the cluster is corrupted.

* `sky down test` does not remove the pod and service from k8s, even when such record exists in local db.
  I think this is because k8s provider does not return the ray pod in its `non_terminated_nodes` method; and ray stack which calls it - ignores and leaves the ray node as is (i.e. will not eventually call to provider's `terminate_nodes`)

**Comment by romilbhardwaj** [comment]
Ran into this again when trying to run Nemo on a k8s cluster with n1-standard-8 VMs. This time the pod was evicted rather than OOMKilled:
```
Events:
  Type     Reason   Age   From     Message
  ----     ------   ----  ----     -------
  Warning  Evicted  27m   kubelet  The node was low on resource: memory. Threshold quantity: 100Mi, available: 47408Ki. Container ray-node was using 24515276Ki, request is 24G, has larger consumption of memory.
  Normal   Killing  27m   kubelet  Stopping container ray-node
```

**Comment by romilbhardwaj** [comment]
Ran into this again when trying to sft llama4 maverick on a multi-node SkyPilot cluster. Pod got OOMKilled, cluster state got set to INIT. 

We should have better indicators in `sky status` about what happened to the pod.

**Comment by kyuds** [comment]
Some behavioral updates while testing and replicating this issue on current master (commit [37ba129](https://github.com/skypilot-org/skypilot/commit/37ba12977758874067e082482a70526fbab9185f))

1. on `sky launch`, we get the log `command exited with code 137`, which I think is sufficient enough for the user (as they know that they are using k8s, and 137 is reserved for OOM
2. on `sky status -r`, the cluster status is NOT reset to `INIT`, but rather it detects that it cannot connect to the head node and it just tries to terminate the cluster, so the cluster record is deleted. That being said, the OOMKilled pod is still not cleaned up, so I guess I could implement logic to do that? ** actually, if you have multiple pods, and if some are still alive, then the cluster will transition to INIT as described in the original issue. 

feedback please @romilbhardwaj

**Comment by romilbhardwaj** [comment]
1. is ok.
2. requires more thought. Is there a good way to surface this information to the user instead of silently deleting the cluster? Same for multi-node clusters - INIT is ok but can it surface more information?

**Comment by Michaelvll** [comment]
Another user ran into this issue, where the cluster disappear from `sky status` and there is no good way to inspect the reason, unless using kubectl commands.

For evicted pod, we can probably show the details for the cluster history in the dashboard, with reason for the termination.

**Comment by kyuds** [comment]
> 2. requires more thought. Is there a good way to surface this information to the user instead of silently deleting the cluster? Same for multi-node clusters - INIT is ok but can it surface more information?

I think this is possible by creating a new cluster status like `ClusterStatus.FAILED`, and have custom error strings when it does reach that case. I just want to confirm if adding a new cluster status enum is ok in terms of a design choice before proceeding to explore that idea further.

**Comment by kyuds** [comment]
Actually, now that we have #6590 , I think we can implement this much better :)
