### ISSUE TITLE
[Examples] Resnet family of examples does not work

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2358]
Repro: `sky launch -c resnet resnet_app.yaml` (or any other `resnet_app*` YAML)

Fails ([`resnet_app.yaml` log](https://gist.github.com/romilbhardwaj/b06f97303853f265d29a7d50ab258da7), [`resnet_app_storage_spot.yaml` log](https://gist.github.com/romilbhardwaj/6188f5ef51c4bda776b17166c682dd13)):
```
(resnet-app, pid=14309) INFO:tensorflow:training_loop marked as finished
(resnet-app, pid=14309) I0807 06:53:28.586464 139664812836672 error_handling.py:115] training_loop marked as finished
(resnet-app, pid=14309) WARNING:tensorflow:Reraising captured error
(resnet-app, pid=14309) W0807 06:53:28.586674 139664812836672 error_handling.py:149] Reraising captured error
(resnet-app, pid=14309) Traceback (most recent call last):
(resnet-app, pid=14309)   File "/opt/conda/envs/resnet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
(resnet-app, pid=14309)     return fn(*args)
(resnet-app, pid=14309)   File "/opt/conda/envs/resnet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
(resnet-app, pid=14309)     target_list, run_metadata)
(resnet-app, pid=14309)   File "/opt/conda/envs/resnet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
(resnet-app, pid=14309)     run_metadata)
(resnet-app, pid=14309) tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
(resnet-app, pid=14309)          [[{{node max_pooling2d/MaxPool}}]]
```

Appears to be an issue with cudnn paths - `python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"` also does not list any GPUs.

**Comment by romilbhardwaj** [comment]
Ah good catch - indeed a duplicate of #2207. Closing.
