### ISSUE TITLE
[Azure] Throw error on `fetchers.fetch_azure --all-regions`

### ISSUE THREAD

**Issue by sunny0826** [skypilot-org/skypilot#2548]
When using the command:

```shell
python -m sky.clouds.service_catalog.data_fetchers.fetch_azure --all-regions
```

Throw these errors:

```console
Done fetching pricing eastasia
Getting pricing for switzerlandwest
Done fetching pricing switzerlandwest
Exception ignored in: <module 'threading' from '/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/threading.py", line 1355, in _shutdown
    def _shutdown():
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/site-packages/ray/_private/worker.py", line 1723, in sigterm_handler
    sys.exit(signum)
SystemExit: 15
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/site-packages/sky/clouds/service_catalog/data_fetchers/fetch_azure.py", line 95, in get_pricing_df
    assert 'productName' in df.columns, (region, df.columns)
AssertionError: ('brazilus', RangeIndex(start=0, stop=0, step=1))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/site-packages/sky/clouds/service_catalog/data_fetchers/fetch_azure.py", line 260, in <module>
    instance_df = get_all_regions_instance_types_df(region_filter)
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/site-packages/sky/clouds/service_catalog/data_fetchers/fetch_azure.py", line 154, in get_all_regions_instance_types_df
    dfs = dfs.get()
  File "/Users/guoxudong/opt/anaconda3/envs/sky/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AssertionError: ('brazilus', RangeIndex(start=0, stop=0, step=1))
```

Looks like `brazilus` should be added to this list: https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/service_catalog/data_fetchers/fetch_azure.py#L29-L34.

**Comment by concretevitamin** [comment]
Thanks for fixing this @sunny0826!
