### ISSUE TITLE
Ctrl-C failed to terminate the `sky launch` process

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#2664]
After first Ctrl+C, it successfully printed `Aborted` but the process is still running. I Ctrl+C the second times and it shows some traceback on threading join. I suspect it is some threads that not respond to the Ctrl+C?
```bash
I 10-05 11:10:03 provisioner.py:360] Successfully provisioned or found existing instance.
Clusters
NAME             LAUNCHED    RESOURCES            STATUS  AUTOSTOP  COMMAND                 
sky-89fa-memory  2 mins ago  1x AWS(m6i.2xlarge)  INIT    -         sky launch --cloud aws  


Aborted!
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/memory/install/miniconda3/envs/sky-dev/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/home/memory/install/miniconda3/envs/sky-dev/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/home/memory/install/miniconda3/envs/sky-dev/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by Michaelvll** [comment]
This seems not related to the new provisioner but the `spot queue` showing process. Removing the `New Provisioner` from the title now.
