### ISSUE TITLE
[k8s] GPU labeler may not work with EKS using very long node name

### ISSUE THREAD

**Issue by lhttjdr** [skypilot-org/skypilot#2752]
The gpu labeler script will generate a job name by appending node name to `sky-gpu-labeler-`.

https://github.com/skypilot-org/skypilot/blob/da2d6ecf490c8503f55c5ee54fbdc544fc622ff1/sky/utils/kubernetes/gpu_labeler.py#L105

Unfortunately, the node name in EKS is very long with format `ip-xxx-xxx-xxx-xxx.<region>.compute.internal`. Thus the length of labels may exceed 63 characters, which is not allowed by Kubernetes.

```
Found 1 GPU nodes in the cluster
Traceback (most recent call last):
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/sky/utils/kubernetes/gpu_labeler.py", line 155, in <module>
    main()
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/sky/utils/kubernetes/gpu_labeler.py", line 151, in main
    label()
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/sky/utils/kubernetes/gpu_labeler.py", line 112, in label
    batch_v1.create_namespaced_job(namespace, job_manifest)
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/api/batch_v1_api.py", line 210, in create_namespaced_job
    return self.create_namespaced_job_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/api/batch_v1_api.py", line 309, in create_namespaced_job_with_http_info
    return self.api_client.call_api(
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/rest.py", line 279, in POST
    return self.request("POST", url,
  File "/home/demo/anaconda3/envs/sky/lib/python3.8/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'bca2d39d-2bd1-49a9-bde8-02875b492a6a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '25367c57-0436-4946-9f6d-c3e42f89259d', 'X-Kubernetes-Pf-Prioritylevel-Uid': '55796b3e-7ff6-4375-85cd-02754b323999', 'Date': 'Fri, 03 Nov 2023 01:46:51 GMT', 'Content-Length': '1376'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Job.batch \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\" is invalid: [metadata.labels: Invalid value: \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\": must be no more than 63 characters, spec.template.labels: Invalid value: \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\": must be no more than 63 characters]","reason":"Invalid","details":{"name":"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal","group":"batch","kind":"Job","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\": must be no more than 63 characters","field":"metadata.labels"},{"reason":"FieldValueInvalid","message":"Invalid value: \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\": must be no more than 63 characters","field":"metadata.labels"},{"reason":"FieldValueInvalid","message":"Invalid value: \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\": must be no more than 63 characters","field":"spec.template.labels"},{"reason":"FieldValueInvalid","message":"Invalid value: \"sky-gpu-labeler-ip-172-31-15-178.ap-northeast-1.compute.internal\": must be no more than 63 characters","field":"spec.template.labels"}]},"code":422}
```

It's not a good idea to use node name. If you want to avoid conflictions, I think something like `sky-gpu-labeler-${md5_32char(node_name)}` can keep length always less than 63.

**Comment by romilbhardwaj** [comment]
Thanks for catching and raising this @lhttjdr! The `-${md5_32char(node_name)}` change makes a sense - if you'd like to contribute, we'll be very happy to accept a PR to fix this :)

**Comment by Michaelvll** [comment]
Just a note, we have an existing function that handles the case where cluster name is too long. We can probably do something similar here https://github.com/skypilot-org/skypilot/blob/53ba415bb2f6ee72dcbe23edee765bcf6f1e1fe3/sky/backends/backend_utils.py#L901
