### ISSUE TITLE
[Benchmark] TypeError: '<' not supported between instances of 'NoneType' and 'JobStatus'

### ISSUE THREAD

**Issue by csaroff** [skypilot-org/skypilot#2765]
I created a benchmark that included a candidate `- {accelerators: A100:8}`.

```bash
sky bench launch benchmark.yaml --benchmark hydra-3eps
```

At the time, no nodes were available in GCP that could satisfy that candidate, so it wasn't provisioned.

Unfortunately, when I went to check the results of the benchmark, I received the following error:

```bash
$ sky bench show hydra-3eps                               
Traceback (most recent call last):
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/cli.py", line 1162, in invoke
    return super().invoke(ctx)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/cli.py", line 1162, in invoke
    return super().invoke(ctx)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/cli.py", line 4368, in benchmark_show
    benchmark_utils.update_benchmark_state(benchmark)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/benchmark/benchmark_utils.py", line 595, in update_benchmark_state
    _parallel_run_with_interrupt_handling(_update_with_progress_bar,
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/benchmark/benchmark_utils.py", line 202, in _parallel_run_with_interrupt_handling
    return list(p.imap(func, args))
  File "/opt/homebrew/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/opt/homebrew/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/benchmark/benchmark_utils.py", line 585, in _update_with_progress_bar
    message = _update_benchmark_result(arg)
  File "/Users/csaroff/code/bioticsai/ultrasound_classifier/venv/lib/python3.9/site-packages/sky/benchmark/benchmark_utils.py", line 325, in _update_benchmark_result
    job_status < job_lib.JobStatus.RUNNING):
TypeError: '<' not supported between instances of 'NoneType' and 'JobStatus'
```

**Comment by csaroff** [comment]
I'm not sure if it's related to the failed candidate, but it also appears that all of the benchmark clusters were kept running throughout the entire benchmark(even though some would have definitely completed sooner). They all have a duration of exactly `2h 2m 2s`

**Comment by concretevitamin** [comment]
Thanks for the report @csaroff. Could you help test if #2767 fixes this TypeError?

**Comment by csaroff** [comment]
It works! Amazing turn-around speed. Thanks for the help @concretevitamin
