### ISSUE TITLE
[Spot/Serve] Allow multiple resources candidate for controller in `~/.sky/config.yaml`

### ISSUE THREAD

**Issue by Kenadyi** [skypilot-org/skypilot#2869]
```
(sky) skypilot@kenadyinampudi:~$ sky spot launch  skypilot_gcp_v2.yaml
Task from YAML spec: skypilot_gcp_v2.yaml
Managed spot job 'sky-a49d-skypilot' will be launched on (estimated):
I 12-15 18:59:42 optimizer.py:694] == Optimizer ==
I 12-15 18:59:42 optimizer.py:705] Target: minimizing cost
I 12-15 18:59:42 optimizer.py:717] Estimated cost: $0.0 / hour
I 12-15 18:59:42 optimizer.py:717]
I 12-15 18:59:42 optimizer.py:840] Considered resources (1 node):
I 12-15 18:59:42 optimizer.py:910] --------------------------------------------------------------------------------------------------
I 12-15 18:59:42 optimizer.py:910]  CLOUD   INSTANCE              vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 12-15 18:59:42 optimizer.py:910] --------------------------------------------------------------------------------------------------
I 12-15 18:59:42 optimizer.py:910]  GCP     n2-standard-2[Spot]   2       8         -              us-west1-a    0.03          ✔
I 12-15 18:59:42 optimizer.py:910] --------------------------------------------------------------------------------------------------
I 12-15 18:59:42 optimizer.py:910]
Launching the spot job 'sky-a49d-skypilot'. Proceed? [Y/n]: y
I 12-15 18:59:48 controller_utils.py:394] Translating file_mounts with local source paths to SkyPilot Storage...
I 12-15 18:59:48 controller_utils.py:444] Folder in local file mount '~/flexnet_11_18_3_1_linux64' will be synced to SkyPilot storage skypilot-filemounts-folder-skypilot-cd427500-0.
I 12-15 18:59:48 controller_utils.py:492] Uploading sources to cloud storage. See: sky storage ls
Traceback (most recent call last):
  File "/home/skypilot/miniconda3/envs/sky/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 1167, in invoke
    return super().invoke(ctx)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 1167, in invoke
    return super().invoke(ctx)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 3948, in spot_launch
    sky.spot_launch(dag,
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/execution.py", line 658, in spot_launch
    controller_utils.maybe_translate_local_file_mounts_and_sync_up(
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/controller_utils.py", line 494, in maybe_translate_local_file_mounts_and_sync_up
    task.sync_storage_mounts()
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/task.py", line 954, in sync_storage_mounts
    storage.add_store(store_type)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/data/storage.py", line 802, in add_store
    store = store_cls(
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/data/storage.py", line 1404, in __init__
    super().__init__(name, source, region, is_sky_managed,
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/data/storage.py", line 234, in __init__
    self.initialize()
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/data/storage.py", line 1522, in initialize
    self.client = gcp.storage_client()
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/adaptors/gcp.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/adaptors/gcp.py", line 46, in storage_client
    from google.cloud import storage
ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)

```

**Comment by concretevitamin** [comment]
Looks like GCP SDK is missing. Does running `pip install -U "skypilot-nightly[gcp]"` resolve this?

**Comment by Kenadyi** [comment]
@concretevitamin ,
No it did not fix it 

```
I 12-15 22:43:27 controller_utils.py:394] Translating file_mounts with local source paths to SkyPilot Storage...
I 12-15 22:43:27 controller_utils.py:444] Folder in local file mount '~/flexnet_11_18_3_1_linux64' will be synced to SkyPilot storage skypilot-filemounts-folder-skypilot-2855221f-0.
I 12-15 22:43:27 controller_utils.py:492] Uploading sources to cloud storage. See: sky storage ls
I 12-15 22:43:32 storage.py:1790] Created GCS bucket skypilot-filemounts-folder-skypilot-2855221f-0 in US-CENTRAL1 with storage class STANDARD
Traceback (most recent call last):
  File "/home/skypilot/miniconda3/envs/sky/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 1167, in invoke
    return super().invoke(ctx)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 1167, in invoke
    return super().invoke(ctx)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/cli.py", line 3948, in spot_launch
    sky.spot_launch(dag,
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/execution.py", line 668, in spot_launch
    controller_resources = (controller_utils.get_controller_resources(
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/utils/controller_utils.py", line 272, in get_controller_resources
    controller_resources = resources.Resources.from_yaml_config(
  File "/home/skypilot/miniconda3/envs/sky/lib/python3.8/site-packages/sky/resources.py", line 1159, in from_yaml_config
    assert not config, f'Invalid resource args: {config.keys()}'
AssertionError: Invalid resource args: dict_keys(['any_of'])
```

**Comment by cblmemo** [comment]
Hi @Kenadyi ! We have an ongoing PR #2833 to fix this problem. For now, you can dropping the any_of field in ~/.sky/config.yaml for now and use a single resources for your controller.
