### ISSUE TITLE
[core] Launching a large cluster fails with `Too many open files`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3002]
Trying to launch a 75 node cluster fails with `Too many open files` during setup phase. Increasing ulimit with `ulimit -n 65535` does not help, stays stuck on `⠙ Preparing SkyPilot runtime (2/3 - dependencies)` for ~45 min+. 

Repro:

```
$ sky launch --num-nodes=75 --cpus 2+ --use-spot --down -c test --cloud aws

...
D 01-19 08:00:11 provisioner.py:503] Stacktrace:
D 01-19 08:00:11 provisioner.py:503] Traceback (most recent call last):
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/provisioner.py", line 496, in post_provision_runtime_setup
D 01-19 08:00:11 provisioner.py:503]     return _post_provision_setup(cloud_name,
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/provisioner.py", line 409, in _post_provision_setup
D 01-19 08:00:11 provisioner.py:503]     instance_setup.internal_file_mounts(cluster_name.name_on_cloud,
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 84, in wrapper
D 01-19 08:00:11 provisioner.py:503]     return func(*args, **kwargs)
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 403, in internal_file_mounts
D 01-19 08:00:11 provisioner.py:503]     _parallel_ssh_with_cache(
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 124, in _parallel_ssh_with_cache
D 01-19 08:00:11 provisioner.py:503]     return [future.result() for future in results]
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 124, in <listcomp>
D 01-19 08:00:11 provisioner.py:503]     return [future.result() for future in results]
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/tools/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
D 01-19 08:00:11 provisioner.py:503]     return self.__get_result()
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/tools/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
D 01-19 08:00:11 provisioner.py:503]     raise self._exception
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/tools/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
D 01-19 08:00:11 provisioner.py:503]     result = self.fn(*self.args, **self.kwargs)
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/metadata_utils.py", line 45, in wrapper
D 01-19 08:00:11 provisioner.py:503]     return function(*args, **kwargs)
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 401, in _setup_node
D 01-19 08:00:11 provisioner.py:503]     _internal_file_mounts(common_file_mounts, runner, log_path)
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 68, in retry
D 01-19 08:00:11 provisioner.py:503]     raise e
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 65, in retry
D 01-19 08:00:11 provisioner.py:503]     return func(*args, **kwargs)
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/instance_setup.py", line 372, in _internal_file_mounts
D 01-19 08:00:11 provisioner.py:503]     rc, stdout, stderr = runner.run(mkdir_command,
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/command_runner.py", line 343, in run
D 01-19 08:00:11 provisioner.py:503]     return log_lib.run_with_log(' '.join(command),
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/skylet/log_lib.py", line 188, in run_with_log
D 01-19 08:00:11 provisioner.py:503]     with subprocess.Popen(cmd,
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/tools/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
D 01-19 08:00:11 provisioner.py:503]     self._execute_child(args, executable, preexec_fn, close_fds,
D 01-19 08:00:11 provisioner.py:503]   File "/Users/romilb/tools/anaconda3/lib/python3.9/subprocess.py", line 1720, in _execute_child
D 01-19 08:00:11 provisioner.py:503]     errpipe_read, errpipe_write = os.pipe()
D 01-19 08:00:11 provisioner.py:503] OSError: [Errno 24] Too many open files
```

[Full logs](https://gist.github.com/romilbhardwaj/2f65215442030012a5d0a87e8d9b1b3a).

**Comment by romilbhardwaj** [comment]
Update - retried with `ulimit -n 65535` in a new shell and provisioning succeeded. Worth updating the docs for folks running into this.

**Comment by concretevitamin** [comment]
Can reproduce. We may want to fix this in the provisioner too.

`provision.log` indicates it's the parallel filemount syncing causing this trouble, so we should use a more bounded thread pool:
```
...

I 01-19 09:12:57 instance_setup.py:70] _internal_file_mounts: Retrying in 0.9 seconds, due to [Errno 24] Too many open files
I 01-19 09:13:00 instance_setup.py:70] _internal_file_mounts: Retrying in 0.7 seconds, due to [Errno 24] Too many open files
I 01-19 09:13:31 instance_setup.py:86] --------------------End:   internal_file_mounts --------------------
I 01-19 09:13:31 instance_setup.py:86] 
E 01-19 09:13:31 provisioner.py:541] *** Failed setting up cluster. ***
...
D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/provision/instance_setup.py", line 372, in _internal_file_mounts
D 01-19 09:13:31 provisioner.py:542]     rc, stdout, stderr = runner.run(mkdir_command,
D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/utils/command_runner.py", line 343, in run
D 01-19 09:13:31 provisioner.py:542]     return log_lib.run_with_log(' '.join(command),
D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/skylet/log_lib.py", line 188, in run_with_log
D 01-19 09:13:31 provisioner.py:542]     with subprocess.Popen(cmd,
D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/anaconda/envs/py39/lib/python3.9/subprocess.py", line 829, in __init__
D 01-19 09:13:31 provisioner.py:542]     errread, errwrite) = self._get_handles(stdin, stdout, stderr)
D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/anaconda/envs/py39/lib/python3.9/subprocess.py", line 1607, in _get_handles
D 01-19 09:13:31 provisioner.py:542]     c2pread, c2pwrite = os.pipe()
D 01-19 09:13:31 provisioner.py:542] OSError: [Errno 24] Too many open files

...
```
cc @Michaelvll @suquark

**Comment by Michaelvll** [comment]
> Can reproduce. We may want to fix this in the provisioner too.
> 
> `provision.log` indicates it's the parallel filemount syncing causing this trouble, so we should use a more bounded thread pool:
> 
> ```
> ...
> 
> I 01-19 09:12:57 instance_setup.py:70] _internal_file_mounts: Retrying in 0.9 seconds, due to [Errno 24] Too many open files
> I 01-19 09:13:00 instance_setup.py:70] _internal_file_mounts: Retrying in 0.7 seconds, due to [Errno 24] Too many open files
> I 01-19 09:13:31 instance_setup.py:86] --------------------End:   internal_file_mounts --------------------
> I 01-19 09:13:31 instance_setup.py:86] 
> E 01-19 09:13:31 provisioner.py:541] *** Failed setting up cluster. ***
> ...
> D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/provision/instance_setup.py", line 372, in _internal_file_mounts
> D 01-19 09:13:31 provisioner.py:542]     rc, stdout, stderr = runner.run(mkdir_command,
> D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/utils/command_runner.py", line 343, in run
> D 01-19 09:13:31 provisioner.py:542]     return log_lib.run_with_log(' '.join(command),
> D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/skylet/log_lib.py", line 188, in run_with_log
> D 01-19 09:13:31 provisioner.py:542]     with subprocess.Popen(cmd,
> D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/anaconda/envs/py39/lib/python3.9/subprocess.py", line 829, in __init__
> D 01-19 09:13:31 provisioner.py:542]     errread, errwrite) = self._get_handles(stdin, stdout, stderr)
> D 01-19 09:13:31 provisioner.py:542]   File "/Users/zongheng/anaconda/envs/py39/lib/python3.9/subprocess.py", line 1607, in _get_handles
> D 01-19 09:13:31 provisioner.py:542]     c2pread, c2pwrite = os.pipe()
> D 01-19 09:13:31 provisioner.py:542] OSError: [Errno 24] Too many open files
> 
> ...
> ```
> 
> cc @Michaelvll @suquark

Good catch! We can try to reduce the parallelism to mitigate the problem.
