### ISSUE TITLE
[k8s] `sky down --purge` fails on Kubernetes clusters that no longer exist

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3013]
`sky down --purge` should remove cluster entries for Kubernetes clusters that no longer exist (e.g., user deleted EKS cluster or ran `sky local down` or kubeconfig no longer exists). However, it fails with a hard `ValueError` (see below). Seems to be introduced after #2713, since the same works fine on the 0.4.1 release. 

Repro:
1. `sky local up`
2. `sky launch -c test --cloud kubernetes -- echo hi`
3. `rm ~/.kube/config`
4. `sky down test --purge` fails with a hard error (instead of purging).:
```
Traceback (most recent call last):
  File "/Users/romilb/tools/anaconda3/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 1168, in invoke
    return super().invoke(ctx)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 2908, in down
    _down_or_stop_clusters(clusters,
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 3207, in _down_or_stop_clusters
    subprocess_utils.run_in_parallel(_down_or_stop, clusters)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/subprocess_utils.py", line 54, in run_in_parallel
    return list(p.imap(func, args))
  File "/Users/romilb/tools/anaconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/Users/romilb/tools/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 3179, in _down_or_stop
    core.down(name, purge=purge)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/core.py", line 381, in down
    backend.teardown(handle, terminate=True, purge=purge)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/backend.py", line 115, in teardown
    self._teardown(handle, terminate, purge)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/cloud_vm_ray_backend.py", line 3491, in _teardown
    self.teardown_no_lock(
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/cloud_vm_ray_backend.py", line 3998, in teardown_no_lock
    self.post_teardown_cleanup(handle, terminate, purge)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/backends/cloud_vm_ray_backend.py", line 4084, in post_teardown_cleanup
    provision_lib.cleanup_ports(repr(cloud), cluster_name_on_cloud,
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/__init__.py", line 42, in _wrapper
    return impl(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/kubernetes/network.py", line 105, in cleanup_ports
    _cleanup_ports_for_loadbalancer(
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/kubernetes/network.py", line 120, in _cleanup_ports_for_loadbalancer
    network_utils.delete_namespaced_service(
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/provision/kubernetes/network_utils.py", line 148, in delete_namespaced_service
    core_api = kubernetes.core_api()
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/adaptors/kubernetes.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/adaptors/kubernetes.py", line 93, in core_api
    _load_config()
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/adaptors/kubernetes.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/adaptors/kubernetes.py", line 85, in _load_config
    raise ValueError(err_str) from None
ValueError: Failed to load Kubernetes configuration. Please check if your kubeconfig file is valid. Error: Invalid kube-config file. No configuration found.
```

Should also add a test for this case.

**Comment by landscapepainter** [comment]
Found other related error as well:
repo:
1.`sky local up`
2.`rm ~/.kube/config`
3.`sky launch --cloud gcp -y`

```
Traceback (most recent call last):
  File "/opt/conda/envs/sky-dev/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/cli.py", line 1168, in invoke
    return super().invoke(ctx)
  File "/opt/conda/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/sky-dev/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/cli.py", line 1458, in launch
    _launch_with_confirm(task,
  File "/home/gcpuser/skypilot/sky/cli.py", line 855, in _launch_with_confirm
    sky.launch(
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/execution.py", line 495, in launch
    return execute(
  File "/home/gcpuser/skypilot/sky/execution.py", line 312, in execute
    handle = backend.provision(task,
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/backends/backend.py", line 56, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
  File "/home/gcpuser/skypilot/sky/backends/cloud_vm_ray_backend.py", line 2734, in _provision
    config_dict = retry_provisioner.provision_with_retries(
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/backends/cloud_vm_ray_backend.py", line 2012, in provision_with_retries
    config_dict = self._retry_zones(
  File "/home/gcpuser/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1449, in _retry_zones
    config_dict = backend_utils.write_cluster_config(
  File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/home/gcpuser/skypilot/sky/backends/backend_utils.py", line 982, in write_cluster_config
    _optimize_file_mounts(tmp_yaml_path)
  File "/home/gcpuser/skypilot/sky/backends/backend_utils.py", line 278, in _optimize_file_mounts
    subprocess.run(
  File "/opt/conda/envs/sky-dev/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cp -r '/home/gcpuser/.kube/config' /tmp/tmpgpi7gpi8/36d21cd9-87dc-4ad4-965f-cb017509e3a9' returned non-zero exit status 1.
```

**Comment by Michaelvll** [comment]
Having the same issue here. I have to go to the sqlite table to delete the cluster as the `sky down` takes forever, after I removed the GKE cluster.
