### ISSUE TITLE
[Runpod] Tearing down Runpod deployment before UP throws IP error

### ISSUE THREAD

**Issue by tyler-griggs** [skypilot-org/skypilot#3029]
I'm getting an error when using RunPod. When I try to run `sky down -y [cluster-name]` I get a key error from some of the skypilot runpod provisioning code. The instance that I'm trying to bring down is still in INIT and is not yet UP.

```
Traceback (most recent call last):
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/cli.py", line 1168, in invoke
    return super().invoke(ctx)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/cli.py", line 2908, in down
    _down_or_stop_clusters(clusters,
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/cli.py", line 3207, in _down_or_stop_clusters
    subprocess_utils.run_in_parallel(_down_or_stop, clusters)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/subprocess_utils.py", line 54, in run_in_parallel
    return list(p.imap(func, args))
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/cli.py", line 3179, in _down_or_stop
    core.down(name, purge=purge)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/core.py", line 381, in down
    backend.teardown(handle, terminate=True, purge=purge)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 315, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/backend.py", line 115, in teardown
    self._teardown(handle, terminate, purge)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 3491, in _teardown
    self.teardown_no_lock(
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 3813, in teardown_no_lock
    self.run_on_head(handle, 'ray stop --force')
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 4219, in run_on_head
    external_ips = handle.external_ips(max_attempts=_FETCH_IP_MAX_ATTEMPTS)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2411, in external_ips
    self.update_cluster_ips(max_attempts=max_attempts)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2329, in update_cluster_ips
    cluster_feasible_ips = backend_utils.get_node_ips(
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/utils/common_utils.py", line 336, in _record
    return f(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/backends/backend_utils.py", line 1398, in get_node_ips
    metadata = provision_lib.get_cluster_info(
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/provision/__init__.py", line 42, in _wrapper
    return impl(*args, **kwargs)
  File "/Users/tylergriggs/miniconda3/envs/acc-mix/lib/python3.8/site-packages/sky/provision/runpod/instance.py", line 165, in get_cluster_info
    internal_ip=instance_info['internal_ip'],
KeyError: 'internal_ip'
```

**Comment by Michaelvll** [comment]
I could reproduce this by:
1. `sky launch -c test-runpod --cloud runpod --gpus RTX3090`
2. ctrl-c during the `I 01-30 00:00:31 instance.py:102] Waiting for instances to be ready: (0/1).`
3. `sky down test-runpod`
