### ISSUE TITLE
[k8s] `boto3` from base GPU image is stale, causes `test_huggingface` to fail

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3158]
`rayproject/ray:2.4.0-py310-gpu`, the base image for our GPU image, uses `boto3==1.4.8`. This version fails on importing in py310, which is the default python version we use:

```
>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/ray/anaconda3/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/session.py", line 25, in <module>
    import botocore.configloader
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored.requests.exceptions import ConnectionError
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/ray/anaconda3/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/ray/anaconda3/lib/python3.10/collections/__init__.py)
```

This causes our `test_huggingface` to fail since `accelerate` now imports boto3 for sagemaker integration if it is installed, and fails on import. see [logs](https://gist.github.com/romilbhardwaj/b5ebd85342deaabaa1f0555ed6cae910).

We should remove boto3 from our image and let skypilot runtime install its latest version it when necessary. 

Since this involves updating the gpu image, we should batch this fix with #2826 to minimize testing/deployment burden.

**Comment by romilbhardwaj** [comment]
Fixed in #2826.
