### ISSUE TITLE
[K8S] `sky local up` failed on a multi-user system

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#3533]
On commit `7f30ce5e`

Currently the `sky local up` will create a config yaml under `/tmp` and does not clean it up after local cluster creation. If another user on the same Linux OS tries to run `sky local up`, it will show no permission to write on that fail and abort the creation. Should we cleanup the config or make the name of it user-specific to avoid conflict? Logs:

```bash
Creating local cluster...
To view detailed progress: tail -n100 -f ~/sky_logs/sky-2024-05-09-19-57-51-741127/local_up.log
Failed to create local cluster. Full log: ~/sky_logs/sky-2024-05-09-19-57-51-741127/local_up.log
Error: Traceback (most recent call last):
  File "/home/memory/install/miniconda3/envs/sky/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/memory/install/miniconda3/envs/sky/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/memory/skypilot/sky/utils/kubernetes/generate_kind_config.py", line 93, in <module>
    generate_kind_config(args.path, args.port_start, args.port_end,
  File "/home/memory/skypilot/sky/utils/kubernetes/generate_kind_config.py", line 55, in generate_kind_config
    with open(path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/tmp/skypilot-kind.yaml'
```

**Comment by Michaelvll** [comment]
We can probably attach a user hash to the yaml name : )
