### ISSUE TITLE
[K8s] Provision on local k8s cluster failed on `module 'kubernetes.client' has no attribute 'NodeV1Api'`

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#3856]
On a newly-created local k8s cluster, `sky launched` failed due to no `NodeV1Api` found.

Provision logs:

```bash
D 08-21 13:06:41 provisioner.py:162]             "path": "/dev/fuse"
D 08-21 13:06:41 provisioner.py:162]           }
D 08-21 13:06:41 provisioner.py:162]         }
D 08-21 13:06:41 provisioner.py:162]       ],
D 08-21 13:06:41 provisioner.py:162]       "containers": [
D 08-21 13:06:41 provisioner.py:162]         {
D 08-21 13:06:41 provisioner.py:162]           "name": "ray-node",
D 08-21 13:06:41 provisioner.py:162]           "imagePullPolicy": "IfNotPresent",
D 08-21 13:06:41 provisioner.py:162]           "image": "ubuntu:latest",
D 08-21 13:06:41 provisioner.py:162]           "command": [
D 08-21 13:06:41 provisioner.py:162]             "/bin/bash",
D 08-21 13:06:41 provisioner.py:162]             "-c",
D 08-21 13:06:41 provisioner.py:162]             "--"
D 08-21 13:06:41 provisioner.py:162]           ],
D 08-21 13:06:41 provisioner.py:162]           "args": [
D 08-21 13:06:41 provisioner.py:162]             "trap : TERM INT; sleep infinity & wait;"
D 08-21 13:06:41 provisioner.py:162]           ],
D 08-21 13:06:41 provisioner.py:162]           "ports": [
D 08-21 13:06:41 provisioner.py:162]             {
D 08-21 13:06:41 provisioner.py:162]               "containerPort": 22
D 08-21 13:06:41 provisioner.py:162]             },
D 08-21 13:06:41 provisioner.py:162]             {
D 08-21 13:06:41 provisioner.py:162]               "containerPort": 6380
D 08-21 13:06:41 provisioner.py:162]             },
D 08-21 13:06:41 provisioner.py:162]             {
D 08-21 13:06:41 provisioner.py:162]               "containerPort": 10001
D 08-21 13:06:41 provisioner.py:162]             },
D 08-21 13:06:41 provisioner.py:162]             {
D 08-21 13:06:41 provisioner.py:162]               "containerPort": 8266
D 08-21 13:06:41 provisioner.py:162]             }
D 08-21 13:06:41 provisioner.py:162]           ],
D 08-21 13:06:41 provisioner.py:162]           "volumeMounts": [
D 08-21 13:06:41 provisioner.py:162]             {
D 08-21 13:06:41 provisioner.py:162]               "name": "secret-volume",
D 08-21 13:06:41 provisioner.py:162]               "readOnly": true,
D 08-21 13:06:41 provisioner.py:162]               "mountPath": "/etc/secret-volume"
D 08-21 13:06:41 provisioner.py:162]             },
D 08-21 13:06:41 provisioner.py:162]             {
D 08-21 13:06:41 provisioner.py:162]               "mountPath": "/dev/shm",
D 08-21 13:06:41 provisioner.py:162]               "name": "dshm"
D 08-21 13:06:41 provisioner.py:162]             }
D 08-21 13:06:41 provisioner.py:162]           ],
D 08-21 13:06:41 provisioner.py:162]           "resources": {
D 08-21 13:06:41 provisioner.py:162]             "requests": {
D 08-21 13:06:41 provisioner.py:162]               "cpu": 2.0,
D 08-21 13:06:41 provisioner.py:162]               "memory": "2.0G",
D 08-21 13:06:41 provisioner.py:162]               "nvidia.com/gpu": 0
D 08-21 13:06:41 provisioner.py:162]             },
D 08-21 13:06:41 provisioner.py:162]             "limits": {
D 08-21 13:06:41 provisioner.py:162]               "nvidia.com/gpu": 0
D 08-21 13:06:41 provisioner.py:162]             }
D 08-21 13:06:41 provisioner.py:162]           }
D 08-21 13:06:41 provisioner.py:162]         }
D 08-21 13:06:41 provisioner.py:162]       ]
D 08-21 13:06:41 provisioner.py:162]     }
D 08-21 13:06:41 provisioner.py:162]   },
D 08-21 13:06:41 provisioner.py:162]   "count": 1,
D 08-21 13:06:41 provisioner.py:162]   "tags": {},
D 08-21 13:06:41 provisioner.py:162]   "resume_stopped_nodes": true,
D 08-21 13:06:41 provisioner.py:162]   "ports_to_open_on_launch": null
D 08-21 13:06:41 provisioner.py:162] }
I 08-21 13:06:41 provisioner.py:62] Launching on Kubernetes 'sky-2e17-txia'.
I 08-21 13:06:41 config.py:639] _configure_services: service "sky-2e17-txia-4a07-head-ssh" not found, attempting to create it
I 08-21 13:06:41 config.py:642] _configure_services: successfully created service "sky-2e17-txia-4a07-head-ssh"
I 08-21 13:06:41 config.py:639] _configure_services: service "sky-2e17-txia-4a07-head" not found, attempting to create it
I 08-21 13:06:41 config.py:642] _configure_services: successfully created service "sky-2e17-txia-4a07-head"
I 08-21 13:06:41 config.py:264] _configure_autoscaler_service_account: using existing autoscaler_service_account "skypilot-service-account"
I 08-21 13:06:41 config.py:306] _configure_autoscaler_role: using existing autoscaler_role "skypilot-service-account-role"
I 08-21 13:06:41 config.py:370] _configure_autoscaler_role_binding: using existing autoscaler_role_binding "skypilot-service-account-role-binding"
I 08-21 13:06:41 config.py:409] _configure_autoscaler_cluster_role: using existing autoscaler_cluster_role "skypilot-service-account-cluster-role"
I 08-21 13:06:41 config.py:456] _configure_autoscaler_cluster_role_binding: using existing autoscaler_cluster_role_binding "skypilot-service-account-cluster-role-binding"
I 08-21 13:06:41 config.py:306] _configure_autoscaler_role: using existing autoscaler_skypilot_system_role "skypilot-system-service-account-role"
I 08-21 13:06:41 config.py:370] _configure_autoscaler_role_binding: using existing autoscaler_skypilot_system_role_binding "skypilot-system-service-account-role-binding-default"
I 08-21 13:06:41 config.py:70] Port mode is set to ingress, setting up ingress role and role binding.
I 08-21 13:06:41 config.py:306] _configure_autoscaler_role: using existing autoscaler_ingress_role "skypilot-service-account-ingress-role"
I 08-21 13:06:41 config.py:370] _configure_autoscaler_role_binding: using existing autoscaler_ingress_role_binding "skypilot-service-account-ingress-role-binding"
D 08-21 13:06:41 instance.py:507] Found 0 existing pods: []
D 08-21 13:06:41 provisioner.py:171] Failed to provision 'sky-2e17-txia' on Kubernetes (all zones).
D 08-21 13:06:41 provisioner.py:173] bulk_provision for 'sky-2e17-txia' failed. Stacktrace:
D 08-21 13:06:41 provisioner.py:173] Traceback (most recent call last):
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/provision/provisioner.py", line 165, in bulk_provision
D 08-21 13:06:41 provisioner.py:173]     return _bulk_provision(cloud, region, zones, cluster_name,
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/provision/provisioner.py", line 87, in _bulk_provision
D 08-21 13:06:41 provisioner.py:173]     provision_record = provision.run_instances(provider_name,
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/provision/__init__.py", line 47, in _wrapper
D 08-21 13:06:41 provisioner.py:173]     return impl(*args, **kwargs)
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/provision/kubernetes/instance.py", line 659, in run_instances
D 08-21 13:06:41 provisioner.py:173]     return _create_pods(region, cluster_name_on_cloud, config)
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/provision/kubernetes/instance.py", line 523, in _create_pods
D 08-21 13:06:41 provisioner.py:173]     nvidia_runtime_exists = kubernetes_utils.check_nvidia_runtime_class()
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/provision/kubernetes/utils.py", line 1520, in check_nvidia_runtime_class
D 08-21 13:06:41 provisioner.py:173]     runtime_classes = kubernetes.node_api().list_runtime_class()
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/adaptors/kubernetes.py", line 60, in wrapped
D 08-21 13:06:41 provisioner.py:173]     obj = api(*args, **kwargs)
D 08-21 13:06:41 provisioner.py:173]   File "/home/txia/skypilot/sky/adaptors/kubernetes.py", line 150, in node_api
D 08-21 13:06:41 provisioner.py:173]     _node_api = kubernetes.client.NodeV1Api()
D 08-21 13:06:41 provisioner.py:173] AttributeError: module 'kubernetes.client' has no attribute 'NodeV1Api'
D 08-21 13:06:41 provisioner.py:173] 
D 08-21 13:06:41 provisioner.py:178] Terminating the failed cluster.
D 08-21 13:06:41 metadata_utils.py:115] Remove metadata of cluster sky-2e17-txia-4a07.
```

Full logs:

```bash
sky launch --image-id docker:ubuntu:latest --cloud kubernetes
I 08-21 13:06:37 optimizer.py:691] == Optimizer ==
I 08-21 13:06:37 optimizer.py:714] Estimated cost: $0.0 / hour
I 08-21 13:06:37 optimizer.py:714] 
I 08-21 13:06:37 optimizer.py:839] Considered resources (1 node):
I 08-21 13:06:37 optimizer.py:909] ---------------------------------------------------------------------------------------------
I 08-21 13:06:37 optimizer.py:909]  CLOUD        INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 08-21 13:06:37 optimizer.py:909] ---------------------------------------------------------------------------------------------
I 08-21 13:06:37 optimizer.py:909]  Kubernetes   2CPU--2GB   2       2         -              kubernetes    0.00          ✔     
I 08-21 13:06:37 optimizer.py:909] ---------------------------------------------------------------------------------------------
I 08-21 13:06:37 optimizer.py:909] 
Launching a new cluster 'sky-2e17-txia'. Proceed? [Y/n]: 
I 08-21 13:06:38 cloud_vm_ray_backend.py:4354] Creating a new cluster: 'sky-2e17-txia' [1x Kubernetes(2CPU--2GB, image_id={'kubernetes': 'docker:ubuntu:latest'})].
I 08-21 13:06:38 cloud_vm_ray_backend.py:4354] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 08-21 13:06:40 cloud_vm_ray_backend.py:1314] To view detailed progress: tail -n100 -f /home/txia/sky_logs/sky-2024-08-21-13-06-37-732584/provision.log
I 08-21 13:06:41 provisioner.py:62] Launching on Kubernetes 'sky-2e17-txia'.
Clusters
NAME           LAUNCHED        RESOURCES                                                                  STATUS  AUTOSTOP  COMMAND                       
sky-2e17-txia  a few secs ago  1x Kubernetes(2CPU--2GB, image_id={'kubernetes': 'docker:ubuntu:latest...  INIT    -         sky launch --image-id doc...  

Traceback (most recent call last):
  File "/home/txia/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1483, in _retry_zones
    provision_record = provisioner.bulk_provision(
  File "/home/txia/skypilot/sky/provision/provisioner.py", line 165, in bulk_provision
    return _bulk_provision(cloud, region, zones, cluster_name,
  File "/home/txia/skypilot/sky/provision/provisioner.py", line 87, in _bulk_provision
    provision_record = provision.run_instances(provider_name,
  File "/home/txia/skypilot/sky/provision/__init__.py", line 47, in _wrapper
    return impl(*args, **kwargs)
  File "/home/txia/skypilot/sky/provision/kubernetes/instance.py", line 659, in run_instances
    return _create_pods(region, cluster_name_on_cloud, config)
  File "/home/txia/skypilot/sky/provision/kubernetes/instance.py", line 523, in _create_pods
    nvidia_runtime_exists = kubernetes_utils.check_nvidia_runtime_class()
  File "/home/txia/skypilot/sky/provision/kubernetes/utils.py", line 1520, in check_nvidia_runtime_class
    runtime_classes = kubernetes.node_api().list_runtime_class()
  File "/home/txia/skypilot/sky/adaptors/kubernetes.py", line 60, in wrapped
    obj = api(*args, **kwargs)
  File "/home/txia/skypilot/sky/adaptors/kubernetes.py", line 150, in node_api
    _node_api = kubernetes.client.NodeV1Api()
AttributeError: module 'kubernetes.client' has no attribute 'NodeV1Api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/txia/miniconda3/envs/sky-serve/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 367, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/cli.py", line 806, in invoke
    return super().invoke(ctx)
  File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 388, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/cli.py", line 1119, in launch
    _launch_with_confirm(task,
  File "/home/txia/skypilot/sky/cli.py", line 597, in _launch_with_confirm
    sky.launch(
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 388, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 388, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/execution.py", line 458, in launch
    return _execute(
  File "/home/txia/skypilot/sky/execution.py", line 273, in _execute
    handle = backend.provision(task,
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 388, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 367, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/backends/backend.py", line 57, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
  File "/home/txia/skypilot/sky/backends/cloud_vm_ray_backend.py", line 2770, in _provision
    config_dict = retry_provisioner.provision_with_retries(
  File "/home/txia/skypilot/sky/utils/common_utils.py", line 388, in _record
    return f(*args, **kwargs)
  File "/home/txia/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1965, in provision_with_retries
    config_dict = self._retry_zones(
  File "/home/txia/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1514, in _retry_zones
    CloudVmRayBackend().post_teardown_cleanup(
  File "/home/txia/skypilot/sky/backends/cloud_vm_ray_backend.py", line 4048, in post_teardown_cleanup
    provision_lib.cleanup_ports(repr(cloud), cluster_name_on_cloud,
  File "/home/txia/skypilot/sky/provision/__init__.py", line 47, in _wrapper
    return impl(*args, **kwargs)
  File "/home/txia/skypilot/sky/provision/kubernetes/network.py", line 140, in cleanup_ports
    _cleanup_ports_for_ingress(cluster_name_on_cloud=cluster_name_on_cloud,
  File "/home/txia/skypilot/sky/provision/kubernetes/network.py", line 175, in _cleanup_ports_for_ingress
    network_utils.delete_namespaced_ingress(
  File "/home/txia/skypilot/sky/provision/kubernetes/network_utils.py", line 163, in delete_namespaced_ingress
    networking_api.delete_namespaced_ingress(
AttributeError: 'NetworkingV1Api' object has no attribute 'delete_namespaced_ingress'
```

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: latest master, `6101a04198ad50cc04f68a8ca38ca98bfbd72954`

**Comment by romilbhardwaj** [comment]
What's the output of `kubectl version --client`? SkyPilot needs Kubernetes client 1.20 or later.

**Comment by cblmemo** [comment]
> What's the output of `kubectl version --client`? SkyPilot needs Kubernetes client 1.20 or later.

```bash
$ k version --client
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

**Comment by romilbhardwaj** [comment]
Ah sorry, what's your python API version:
```
python -c "import kubernetes;print(kubernetes.__version__)"
```

**Comment by cblmemo** [comment]
> Ah sorry, what's your python API version:
> 
> ```
> python -c "import kubernetes;print(kubernetes.__version__)"
> ```
> 
> Must be 20.0.0 or later.

```bash
$ python -c "import kubernetes;print(kubernetes.__version__)"
17.17.0
```

Oh, good point... Seems like I forgot to update the version. Updating this resolved the problem. Thanks!
