### ISSUE TITLE
[R2] R2 not supported as source in file_mounts

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3946]
```
file_mounts:
  /data:
    source: r2://skypilot-lmsys-chat-1m
    mode: MOUNT
```

```
$ sky launch -c inf task.yaml
Task from YAML spec: inference.yaml
I 09-14 00:05:21 storage.py:536] Verifying bucket for storage skypilot-lmsys-chat-1m
E 09-14 00:05:21 storage.py:1006] Could not upload 'r2://skypilot-lmsys-chat-1m' to store name 'skypilot-lmsys-chat-1m'.
Traceback (most recent call last):
  File "/home/gcpuser/skypilot-dev/sky/data/storage.py", line 1245, in upload
    self._transfer_to_s3()
  File "/home/gcpuser/skypilot-dev/sky/data/storage.py", line 1337, in _transfer_to_s3
    data_transfer.r2_to_s3(self.name, self.name)
  File "/home/gcpuser/skypilot-dev/sky/data/data_transfer.py", line 188, in r2_to_s3
    raise NotImplementedError('Moving data directly from R2 to clouds is '
NotImplementedError: Moving data directly from R2 to clouds is currently not supported. Please specify a local source for the storage object.
```

After some testing, it seems the issue is I have storage created in `~/.sky/state.db` with name `skypilot-lmsys-chat-1m`. After I remove the storage item in `~/.sky/state.db` with `sqlite3`, it seems working again.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by landscapepainter** [comment]
When @Michaelvll encountered the issue described above, I'm assuming an S3 store type with name of `skypilot-lmsys-chat-1m` would have been already created and managed by sky. When `Storage` object was attempted to be created with externally created r2 bucket with an identical name, `skypilot-lmsys-chat-1m`, data from `state.db` on sky managed S3 `AbstractStore` type is read and synced, which caused this error.

Example from the description ends with an error as as `_transfer_to_r2()` method is currently not implemented. However, when I used gcs as source with `gs://skypilot-lmsys-chat-1m-dy`, it synced the sky managed s3 storage with empty bucket at `gs://skypilot-lmsys-chat-1m-dy` removing all the items in s3 storage as `_transfer_to_s3` is implemented.
