### ISSUE TITLE
[Storage][Serve] Surface the error message when SkyServe failed on workdir storage

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#3951]
On the latest master, the service with workdir will fail to sync up their workdir due to assertion errors. Services without workdir do not have this problem. This prevent a common usecase of sky serve and also let a bunch of smoke test to fail. We should fix this.

```bash
$ sky serve up examples/serve/http_server/task.yaml
Service from YAML spec: examples/serve/http_server/task.yaml
Service Spec:
Readiness probe method:           GET /health
Readiness initial delay seconds:  20
Readiness probe timeout seconds:  15
Replica autoscaling policy:       Fixed 2 replicas
Spot Policy:                      No spot fallback policy

Each replica will use the following resources (estimated):
I 09-16 20:57:39 optimizer.py:719] == Optimizer ==
I 09-16 20:57:39 optimizer.py:730] Target: minimizing cost
I 09-16 20:57:39 optimizer.py:742] Estimated cost: $0.0 / hour
I 09-16 20:57:39 optimizer.py:742] 
I 09-16 20:57:39 optimizer.py:867] Considered resources (1 node):
I 09-16 20:57:39 optimizer.py:937] --------------------------------------------------------------------------------------------------------
I 09-16 20:57:39 optimizer.py:937]  CLOUD        INSTANCE             vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 09-16 20:57:39 optimizer.py:937] --------------------------------------------------------------------------------------------------------
I 09-16 20:57:39 optimizer.py:937]  Kubernetes   2CPU--2GB            2       2         -              kubernetes      0.00          ✔     
I 09-16 20:57:39 optimizer.py:937]  AWS          m6i.large            2       8         -              us-east-1       0.10                
I 09-16 20:57:39 optimizer.py:937]  Azure        Standard_D2s_v5      2       8         -              eastus          0.10                
I 09-16 20:57:39 optimizer.py:937]  GCP          n2-standard-2        2       8         -              us-central1-a   0.10                
I 09-16 20:57:39 optimizer.py:937]  RunPod       1x_RTXA4000_SECURE   6       16        RTXA4000:1     CA              0.34                
I 09-16 20:57:39 optimizer.py:937] --------------------------------------------------------------------------------------------------------
I 09-16 20:57:39 optimizer.py:937] 
Launching a new service 'sky-service-93ad'. Proceed? [Y/n]: 
I 09-16 20:57:42 controller_utils.py:600] Translating workdir to SkyPilot Storage...
I 09-16 20:57:42 controller_utils.py:625] Workdir 'examples/serve/http_server' will be synced to cloud storage 'skypilot-workdir-txia-5e091ebd'.
I 09-16 20:57:42 controller_utils.py:698] Uploading sources to cloud storage. See: sky storage ls
E 09-16 20:57:43 storage.py:902] Could not create StoreType.S3 store with name skypilot-workdir-txia-5e091ebd.
AssertionError: ('We only support one store type for now.', {})
```

_Version & Commit info:_
* `sky -c`: `e870839aeed16c118c0eb1f4889efc20006c27c4`

**Comment by cblmemo** [comment]
cc @landscapepainter - is this related to some recent storage update?

**Comment by cblmemo** [comment]
Update - this is due to too many bucket created. We should surface this error to users.

https://github.com/skypilot-org/skypilot/blob/e870839aeed16c118c0eb1f4889efc20006c27c4/sky/data/storage.py#L1465-L1468

```bash
E 09-17 10:04:58 storage.py:902] Could not create StoreType.S3 store with name skypilot-workdir-memory-2972ca61. Error: Attempted to create a bucket skypilot-workdir-memory-2972ca61 but failed.Error: An error occurred (TooManyBuckets) when calling the CreateBucket operation: You have attempted to create more buckets than allowed
```

**Comment by jbohnslav** [comment]
I just got the message `Could not create StoreType.S3` when trying to do `sky jobs launch`. Reverting to `0.8.1` fixes it.

**Comment by cg505** [comment]
@jbohnslav Could you set `export SKYPILOT_DEBUG=1` and share the full logs?

**Comment by ibrahimnd2000** [comment]
```
D 02-19 19:50:08.985 PID=99826 skypilot_config.py:247] using default user config file: ~/.sky/config.yaml
D 02-19 19:50:08.993 PID=99826 skypilot_config.py:514] Config loaded from /Users/muhammad.ibrahim/.sky/config.yaml:
D 02-19 19:50:08.993 PID=99826 skypilot_config.py:514] api_server:
D 02-19 19:50:08.993 PID=99826 skypilot_config.py:514]   endpoint: https://skypilot.test.compactif.ai
D 02-19 19:50:08.993 PID=99826 skypilot_config.py:514] 
D 02-19 19:50:09.071 PID=99826 skypilot_config.py:521] Config syntax check passed for path: /Users/muhammad.ibrahim/.sky/config.yaml
D 02-19 19:50:09.071 PID=99826 skypilot_config.py:274] using default project config file: .sky.yaml
D 02-19 19:50:09.071 PID=99826 skypilot_config.py:666] client config (before task and CLI overrides): 
D 02-19 19:50:09.071 PID=99826 skypilot_config.py:666] api_server:
D 02-19 19:50:09.071 PID=99826 skypilot_config.py:666]   endpoint: https://skypilot.test.compactif.ai
D 02-19 19:50:09.071 PID=99826 skypilot_config.py:666] 
YAML to run: test_job.yaml
D 02-19 19:50:10.243 PID=99826 common.py:410] Health check status: 200
I 02-19 19:50:10.590 PID=99826 common.py:349] ⚙︎ Uploading files to API server
D 02-19 19:50:10.597 PID=99826 storage_utils.py:201]   Excluded files to sync to cluster based on .gitignore.
I 02-19 19:50:11.385 PID=99826 common.py:399] ✓ Files uploaded  View logs: ~/sky_logs/file_uploads/sky-2026-02-19-19-50-10-590150-780c7464.log
D 02-19 18:50:11 skypilot_config.py:299] using default server config file: ~/.sky/config.yaml
D 02-19 18:50:11 skypilot_config.py:514] Config loaded from /root/.sky/config.yaml:
D 02-19 18:50:11 skypilot_config.py:514] jobs:
D 02-19 18:50:11 skypilot_config.py:514]   controller:
D 02-19 18:50:11 skypilot_config.py:514]     consolidation_mode: false
D 02-19 18:50:11 skypilot_config.py:514] 
D 02-19 18:50:11 skypilot_config.py:514] aws:
D 02-19 18:50:11 skypilot_config.py:514]   remote_identity: NO_UPLOAD
D 02-19 18:50:11 skypilot_config.py:514] 
D 02-19 18:50:11 skypilot_config.py:514] rbac:
D 02-19 18:50:11 skypilot_config.py:514]   default_role: user
D 02-19 18:50:11 skypilot_config.py:514] 
D 02-19 18:50:11 skypilot_config.py:514] kubernetes:
D 02-19 18:50:11 skypilot_config.py:514]   allowed_contexts:
D 02-19 18:50:11 skypilot_config.py:514]   - multiversecomputing.teleport.sh-research-dev-hyperpod-use1
D 02-19 18:50:11 skypilot_config.py:514]   - multiversecomputing.teleport.sh-research-dev-hyperpod-eus2
D 02-19 18:50:11 skypilot_config.py:514]   - multiversecomputing.teleport.sh-product-dev-hyperpod-eus2
D 02-19 18:50:11 skypilot_config.py:514]   - multiversecomputing.teleport.sh-product-dev-hyperpod-use1
D 02-19 18:50:11 skypilot_config.py:514] 
D 02-19 18:50:11 skypilot_config.py:521] Config syntax check passed for path: /root/.sky/config.yaml
D 02-19 18:50:11 skypilot_config.py:639] server config: 
D 02-19 18:50:11 skypilot_config.py:639] jobs:
D 02-19 18:50:11 skypilot_config.py:639]   controller:
D 02-19 18:50:11 skypilot_config.py:639]     consolidation_mode: false
D 02-19 18:50:11 skypilot_config.py:639] 
D 02-19 18:50:11 skypilot_config.py:639] aws:
D 02-19 18:50:11 skypilot_config.py:639]   remote_identity: NO_UPLOAD
D 02-19 18:50:11 skypilot_config.py:639] 
D 02-19 18:50:11 skypilot_config.py:639] rbac:
D 02-19 18:50:11 skypilot_config.py:639]   default_role: user
D 02-19 18:50:11 skypilot_config.py:639] 
D 02-19 18:50:11 skypilot_config.py:639] kubernetes:
D 02-19 18:50:11 skypilot_config.py:639]   allowed_contexts:
D 02-19 18:50:11 skypilot_config.py:639]   - multiversecomputing.teleport.sh-research-dev-hyperpod-use1
D 02-19 18:50:11 skypilot_config.py:639]   - multiversecomputing.teleport.sh-research-dev-hyperpod-eus2
D 02-19 18:50:11 skypilot_config.py:639]   - multiversecomputing.teleport.sh-product-dev-hyperpod-eus2
D 02-19 18:50:11 skypilot_config.py:639]   - multiversecomputing.teleport.sh-product-dev-hyperpod-use1
D 02-19 18:50:11 skypilot_config.py:639] 
D 02-19 18:50:11 executor.py:366] override path: ["/Users/muhammad.ibrahim/.sky/config.yaml", null]
D 02-19 18:50:11 skypilot_config.py:424] No active workspace found, using default workspace: default
D 02-19 18:50:11 executor.py:385] 3708548e-f1cb-44af-b442-d92d8facb6dd permission granted to sky.jobs.launch request
D 02-19 18:50:11 executor.py:495] request config: 
D 02-19 18:50:11 executor.py:495] jobs:
D 02-19 18:50:11 executor.py:495]   controller:
D 02-19 18:50:11 executor.py:495]     consolidation_mode: false
D 02-19 18:50:11 executor.py:495] 
D 02-19 18:50:11 executor.py:495] aws:
D 02-19 18:50:11 executor.py:495]   remote_identity: NO_UPLOAD
D 02-19 18:50:11 executor.py:495] 
D 02-19 18:50:11 executor.py:495] rbac:
D 02-19 18:50:11 executor.py:495]   default_role: user
D 02-19 18:50:11 executor.py:495] 
D 02-19 18:50:11 executor.py:495] kubernetes:
D 02-19 18:50:11 executor.py:495]   allowed_contexts:
D 02-19 18:50:11 executor.py:495]   - multiversecomputing.teleport.sh-research-dev-hyperpod-use1
D 02-19 18:50:11 executor.py:495]   - multiversecomputing.teleport.sh-research-dev-hyperpod-eus2
D 02-19 18:50:11 executor.py:495]   - multiversecomputing.teleport.sh-product-dev-hyperpod-eus2
D 02-19 18:50:11 executor.py:495]   - multiversecomputing.teleport.sh-product-dev-hyperpod-use1
D 02-19 18:50:11 executor.py:495] 
D 02-19 18:50:11 skypilot_config.py:424] No active workspace found, using default workspace: default
I 02-19 18:50:11 controller_utils.py:967] ⚙︎ Translating workdir to SkyPilot Storage...
I 02-19 18:50:11 controller_utils.py:1034]   Workdir: '/root/.sky/api_server/clients/15cf5421/file_mounts/Users/muhammad.ibrahim/Work/compactifai-control-plane/src/scripts/orchestration' -> storage: 'skypilot-filemounts-muhammadibrahimmultiversecomputingcom-15cf5421-6ztnfk7t'.
D 02-19 18:50:11 skypilot_config.py:424] No active workspace found, using default workspace: default
E 02-19 18:50:11 storage.py:1222] Could not mount externally created StoreType.S3 store with name 'skypilot-filemounts-muhammadibrahimmultiversecomputingcom-15cf5421-6ztnfk7t'.
D 02-19 19:50:12.945 PID=99826 sdk.py:2006] Got request with error: sky.jobs.launch
E 02-19 19:50:12.945 PID=99826 sdk.py:389] === Traceback on SkyPilot API Server ===
E 02-19 19:50:12.945 PID=99826 sdk.py:389] Traceback (most recent call last):
E 02-19 19:50:12.945 PID=99826 sdk.py:389]   File "/usr/local/lib/python3.10/site-packages/sky/server/requests/executor.py", line 501, in _request_execution_wrapper
E 02-19 19:50:12.945 PID=99826 sdk.py:389]     return_value = func(**request_body.to_kwargs())
E 02-19 19:50:12.945 PID=99826 sdk.py:389]   File "/usr/local/lib/python3.10/site-packages/sky/utils/common_utils.py", line 621, in _record
E 02-19 19:50:12.945 PID=99826 sdk.py:389]     return f(*args, **kwargs)
E 02-19 19:50:12.945 PID=99826 sdk.py:389]   File "/usr/local/lib/python3.10/site-packages/sky/utils/common_utils.py", line 621, in _record
E 02-19 19:50:12.945 PID=99826 sdk.py:389]     return f(*args, **kwargs)
E 02-19 19:50:12.945 PID=99826 sdk.py:389]   File "/usr/local/lib/python3.10/site-packages/sky/jobs/server/core.py", line 349, in launch
E 02-19 19:50:12.945 PID=99826 sdk.py:389]     local_to_controller_file_mounts = _upload_files_to_controller(dag)
E 02-19 19:50:12.945 PID=99826 sdk.py:389]   File "/usr/local/lib/python3.10/site-packages/sky/jobs/server/core.py", line 115, in _upload_files_to_controller
E 02-19 19:50:12.945 PID=99826 sdk.py:389]     controller_utils.maybe_translate_local_file_mounts_and_sync_up(
E 02-19 19:50:12.945 PID=99826 sdk.py:389]   File "/usr/local/lib/python3.10/site-packages/sky/utils/controller_utils.py", line 1184, in maybe_translate_local_file_mounts_and_sync_up
E 02-19 19:50:12.945 PID=99826 sdk.py:389]     assert len(store_types) == 1, (
E 02-19 19:50:12.945 PID=99826 sdk.py:389] AssertionError: ('We only support one store type for now.', {})
E 02-19 19:50:12.945 PID=99826 sdk.py:389] 
D 02-19 19:50:12.946 PID=99826 sdk.py:173] To stream request logs: sky api logs 3708548e-f1cb-44af-b442-d92d8facb6dd
Traceback (most recent call last):
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/bin/sky", line 10, in <module>
    sys.exit(cli())
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/cli.py", line 9, in cli
    command.cli()
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/common_utils.py", line 615, in _record
    return f(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/cli/command.py", line 839, in invoke
    return super().invoke(ctx)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/common_utils.py", line 615, in _record
    return f(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/cli/command.py", line 839, in invoke
    return super().invoke(ctx)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/common_utils.py", line 635, in _record
    return f(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/common_utils.py", line 635, in _record
    return f(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/cli/command.py", line 4639, in jobs_launch
    job_id_handle = _async_call_or_wait(request_id, async_call,
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/cli/command.py", line 269, in _async_call_or_wait
    return sdk.stream_and_get(request_id)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/common_utils.py", line 635, in _record
    return f(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/server/common.py", line 792, in wrapper
    return func(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/annotations.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/server/rest.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/sdk.py", line 2114, in stream_and_get
    return stream_response(request_id,
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/sdk.py", line 169, in stream_response
    return get(request_id)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/common_utils.py", line 635, in _record
    return f(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/utils/annotations.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/sdk.py", line 2016, in get
    _raise_exception_object_on_client(error_obj)
  File "/Users/muhammad.ibrahim/Work/compactifai-control-plane/.venv/lib/python3.10/site-packages/sky/client/sdk.py", line 392, in _raise_exception_object_on_client
    raise e
AssertionError: ('We only support one store type for now.', {})
```
