### ISSUE TITLE
[Core] Head node is still in state setting-up when "Retrying to get head ip" exceeds 3 retries

### ISSUE THREAD

**Issue by HysunHe** [skypilot-org/skypilot#4101]
The backend_utils.WAIT_HEAD_NODE_IP_MAX_ATTEMPTS is set to 3. However, it is possible the head node is not ready after retrying 3 times.

But after some seconds  and retry "sky launch" or "ray get-head-ip",  both works. 

D 10-17 04:17:23 cloud_vm_ray_backend.py:1846] Get head ips from ray up stdout: 10.0.3.104 None
D 10-17 04:17:25 backend_utils.py:1416] Retrying to get head ip.
D 10-17 04:17:32 backend_utils.py:1416] Retrying to get head ip.

Traceback (most recent call last):
  File "/home/opc/skypilot_oci/sky/backends/backend_utils.py", line 1390, in _query_head_ip_with_retries
    out = subprocess_utils.run(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/skypilot_oci/sky/utils/common_utils.py", line 388, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/opc/skypilot_oci/sky/utils/subprocess_utils.py", line 31, in run
    return subprocess.run(cmd,
           ^^^^^^^^^^^^^^^^^^^

========================================================

2024-10-17 04:18:55,501 WARN commands.py:1437 -- Head node (ocid1.instance.oc1.phx.anyhqljty5l3z3ycyb6focwj4lgrxplcdoewqjcg2djwqqgszgd6qqx3rgzq) is in state setting-up.
Traceback (most recent call last):
  File "/home/opc/anaconda3/envs/sky/bin/ray", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/opc/anaconda3/envs/sky/lib/python3.11/site-packages/ray/scripts/scripts.py", line 2614, in main
    return cli()
           ^^^^^
  File "/home/opc/anaconda3/envs/sky/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/anaconda3/envs/sky/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/opc/anaconda3/envs/sky/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==========================================================

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by HysunHe** [comment]
Fixed along with PR https://github.com/skypilot-org/skypilot/pull/4119
