### ISSUE TITLE
[Core] No oci installation abort the `sky launch`

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#4179]
If OCI is not enabled and local python environment does not have oci installation, it breaks the provision process. We should fix this before the 0.7.0 release.

Steps to produce:
1. Start a fresh container using `docker run -it --rm --name skypilot-debug berkeleyskypilot/skypilot-debug /bin/bash`.
2. Installing skypilot w/ AWS: `cd skypilot; pip install -e '.[aws]'
3. `aws configure` and input tokens
4. `sky launch` gives the following output:

```bash
(base) root@6d62005c658d:/sky_repo/skypilot# sky launch
D 10-25 20:45:49 common.py:231] Updated AWS catalog aws/vms.csv.
D 10-25 20:45:49 optimizer.py:292] #### Task<name=sky-cmd>(run=<empty>)
D 10-25 20:45:49 optimizer.py:292]   resources: default instances ####
D 10-25 20:45:49 optimizer.py:317] Defaulting the task's estimated time to 1 hour.
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
D 10-25 20:45:49 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 10-25 20:45:49 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 10-25 20:45:49 optimizer.py:362]   estimated_cost (not incl. egress): $0.5
I 10-25 20:45:50 optimizer.py:881] Considered resources (1 node):
I 10-25 20:45:50 optimizer.py:951] ------------------------------------------------------------------------------------------
I 10-25 20:45:50 optimizer.py:951]  CLOUD   INSTANCE      vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 10-25 20:45:50 optimizer.py:951] ------------------------------------------------------------------------------------------
I 10-25 20:45:50 optimizer.py:951]  AWS     m6i.2xlarge   8       32        -              us-east-1     0.38          ✔     
I 10-25 20:45:50 optimizer.py:951] ------------------------------------------------------------------------------------------
Launching a new cluster 'sky-9922-root'. Proceed? [Y/n]: 
D 10-25 20:45:50 cloud_vm_ray_backend.py:4408] cluster_ever_up: False
D 10-25 20:45:50 cloud_vm_ray_backend.py:4409] record: None
D 10-25 20:45:52 common.py:231] Updated AWS catalog aws/instance_quota_mapping.csv.
D 10-25 20:45:52 common.py:231] Updated AWS catalog aws/images.csv.

Traceback (most recent call last):
  File "/sky_repo/skypilot/sky/adaptors/common.py", line 31, in load_module
    self._module = importlib.import_module(self._module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'oci'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sky_repo/skypilot/sky/clouds/oci.py", line 466, in get_credential_file_mounts
    oci_cfg = oci_adaptor.get_oci_config(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/adaptors/oci.py", line 26, in get_oci_config
    oci_config = oci.config.from_file(file_location=conf_file_path,
                 ^^^^^^^^^^
  File "/sky_repo/skypilot/sky/adaptors/common.py", line 46, in __getattr__
    return getattr(self.load_module(), name)
                   ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/adaptors/common.py", line 36, in load_module
    raise ImportError(self._import_error_message) from e
ImportError: Failed to import dependencies for OCI. Try running: pip install "skypilot[oci]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sky_repo/skypilot/sky/adaptors/common.py", line 31, in load_module
    self._module = importlib.import_module(self._module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'oci'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/sky", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/cli.py", line 818, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/cli.py", line 1131, in launch
    _launch_with_confirm(task,
  File "/sky_repo/skypilot/sky/cli.py", line 609, in _launch_with_confirm
    sky.launch(
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/execution.py", line 454, in launch
    return _execute(
           ^^^^^^^^^
  File "/sky_repo/skypilot/sky/execution.py", line 280, in _execute
    handle = backend.provision(task,
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/backends/backend.py", line 60, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/backends/cloud_vm_ray_backend.py", line 2810, in _provision
    config_dict = retry_provisioner.provision_with_retries(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1988, in provision_with_retries
    config_dict = self._retry_zones(
                  ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1399, in _retry_zones
    config_dict = backend_utils.write_cluster_config(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/backends/backend_utils.py", line 832, in write_cluster_config
    credentials = sky_check.get_cloud_credential_file_mounts(excluded_clouds)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/check.py", line 213, in get_cloud_credential_file_mounts
    cloud_file_mounts = cloud.get_credential_file_mounts()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/clouds/oci.py", line 471, in get_credential_file_mounts
    except (ImportError, oci_adaptor.oci.exceptions.ConfigFileNotFound):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/adaptors/common.py", line 46, in __getattr__
    return getattr(self.load_module(), name)
                   ^^^^^^^^^^^^^^^^^^
  File "/sky_repo/skypilot/sky/adaptors/common.py", line 36, in load_module
    raise ImportError(self._import_error_message) from e
ImportError: Failed to import dependencies for OCI. Try running: pip install "skypilot[oci]"
```

_Version & Commit info:_
* `sky -v`: skypilot, version 1.0.0-dev0
* `sky -c`: skypilot, commit ee708e7aad508fab1b48b1f6f297ebe6fb5dbe63

**Comment by Michaelvll** [comment]
This is being fixed by #4178
