### ISSUE TITLE
[Kubernates] Not user-friendly message shown if Kubernates is not enabled. 

### ISSUE THREAD

**Issue by HysunHe** [skypilot-org/skypilot#4324]
When Kubernates is not enabled, "sky check" shows the following exceptions, which is not user-friendly:

  Kubernetes: disabled
    Reason: Traceback (most recent call last):
  File "/home/hysunhe/prjdev/skypilot/skypilot/sky/adaptors/common.py", line 31, in load_module
    self._module = importlib.import_module(self._module_name)
  File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kubernetes'

**Comment by zpoint** [comment]
[PR](https://github.com/skypilot-org/skypilot/pull/4336) submitted
