### ISSUE TITLE
sky jobs launch on Kubernetes seems not working now

### ISSUE THREAD

**Issue by nkwangleiGIT** [skypilot-org/skypilot#4346]
run the managed job:
```
sky jobs launch --cloud kubernetes --cpus 1 -- echo hi
```

failed with TypeError: 'NoneType' object does not support item assignment

found the issue on master branch with latest code.

**Comment by nkwangleiGIT** [comment]
BTW, what's the design of sky launch and sky jobs launch? it'll be great if there are some related technical docs.

**Comment by concretevitamin** [comment]
> BTW, what's the design of sky launch and sky jobs launch? it'll be great if there are some related technical docs.

Hey @nkwangleiGIT -- just to check, did you mean the differences between these two commands are confusing?

**Comment by romilbhardwaj** [comment]
Hey @nkwangleiGIT 

> failed with TypeError: 'NoneType' object does not support item assignment

Do you have a log? I am unable to reproduce on https://github.com/skypilot-org/skypilot/commit/b8416b8434dd1f2e70e2514d3cac8e7698b32088.

**Comment by nkwangleiGIT** [comment]
> > BTW, what's the design of sky launch and sky jobs launch? it'll be great if there are some related technical docs.
> 
> Hey @nkwangleiGIT -- just to check, did you mean the differences between these two commands are confusing?

yes, from the design and usercases perspective, it'll be helpful.

**Comment by nkwangleiGIT** [comment]
> Hey @nkwangleiGIT
> 
> > failed with TypeError: 'NoneType' object does not support item assignment
> 
> Do you have a log? I am unable to reproduce on [b8416b8](https://github.com/skypilot-org/skypilot/commit/b8416b8434dd1f2e70e2514d3cac8e7698b32088).

here is console log when run the job launch
```
Task from command: echo hi
Managed job 'sky-cmd' will be launched on (estimated):
Considered resources (1 node):
----------------------------------------------------------------------------------------------------
 CLOUD        INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE          COST ($)   CHOSEN   
----------------------------------------------------------------------------------------------------
 Kubernetes   2CPU--2GB   2       2         -              host-cluster-admin   0.00          ✔     
----------------------------------------------------------------------------------------------------
Launching a managed job 'sky-cmd'. Proceed? [Y/n]: y
Launching managed job 'sky-cmd' from jobs controller...
Considered resources (1 node):
-----------------------------------------------------------------------------------------------------
 CLOUD        INSTANCE     vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE          COST ($)   CHOSEN   
-----------------------------------------------------------------------------------------------------
 Kubernetes   8CPU--24GB   8       24        -              host-cluster-admin   0.00          ✔     
-----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/nkwanglei/miniforge3/envs/skypilot/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/nkwanglei/miniforge3/envs/skypilot/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nkwanglei/miniforge3/envs/skypilot/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/cli.py", line 831, in invoke
    return super().invoke(ctx)
  File "/Users/nkwanglei/miniforge3/envs/skypilot/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/cli.py", line 831, in invoke
    return super().invoke(ctx)
  File "/Users/nkwanglei/miniforge3/envs/skypilot/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nkwanglei/miniforge3/envs/skypilot/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nkwanglei/miniforge3/envs/skypilot/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/cli.py", line 3715, in jobs_launch
    managed_jobs.launch(dag,
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/jobs/core.py", line 142, in launch
    sky.launch(task=controller_task,
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/execution.py", line 489, in launch
    return _execute(
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/execution.py", line 285, in _execute
    handle = backend.provision(task,
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/backends/backend.py", line 60, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/backends/cloud_vm_ray_backend.py", line 2781, in _provision
    config_dict = retry_provisioner.provision_with_retries(
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1979, in provision_with_retries
    config_dict = self._retry_zones(
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1399, in _retry_zones
    config_dict = backend_utils.write_cluster_config(
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/backends/backend_utils.py", line 855, in write_cluster_config
    kubernetes_utils.combine_pod_config_fields(
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/provision/kubernetes/utils.py", line 1754, in combine_pod_config_fields
    merge_dicts(
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/provision/kubernetes/utils.py", line 1669, in merge_dicts
    merge_dicts(value, destination[key])
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/provision/kubernetes/utils.py", line 1679, in merge_dicts
    merge_dicts(value[0], destination[key][0])
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/provision/kubernetes/utils.py", line 1669, in merge_dicts
    merge_dicts(value, destination[key])
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/provision/kubernetes/utils.py", line 1669, in merge_dicts
    merge_dicts(value, destination[key])
  File "/Users/nkwanglei/matrix-dc/ray-workspace/skypilot/sky/provision/kubernetes/utils.py", line 1696, in merge_dicts
    destination[key] = value
TypeError: 'NoneType' object does not support item assignment
```

**Comment by nkwangleiGIT** [comment]
btw, ```sky launch  -c my-sky-cluster hello_sky.yaml ``` can work normally, and configuration from ~/.sky/config.yaml and job yaml can work normally.

**Comment by Michaelvll** [comment]
I am not sure if it is because some issue with your existing sky jobs controller cluster. Could you try `sky down sky-jobs-controller-<hash>` (you can find the controller name in `sky status`) and try again?

**Comment by Michaelvll** [comment]
> > > BTW, what's the design of sky launch and sky jobs launch? it'll be great if there are some related technical docs.
> > 
> > 
> > Hey @nkwangleiGIT -- just to check, did you mean the differences between these two commands are confusing?
> 
> yes, from the design and usercases perspective, it'll be helpful.

It would be worth to check: https://skypilot.readthedocs.io/en/latest/examples/managed-jobs.html

**Comment by nkwangleiGIT** [comment]
Seems there is some case that the destination might be None when merge the configuration, I have the config.yaml under ~/.sky/
```
kubernetes:
  pod_config:
    spec:
      containers:
        - resources:
            limits:
              cpu: "8"
              memory: "32Gi"
      nodeSelector:
        kubernetes.io/hostname: gpu-3090-04
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu-3090
        value: "true"
```
Look at the error: https://github.com/skypilot-org/skypilot/blob/master/sky/provision/kubernetes/utils.py#L1696
I think we should ensure the destination is not None, add something like this?
```
+            if destination is None:
+               destination = {}
            destination[key] = value
```

**Comment by nkwangleiGIT** [comment]
Another issue in the sky/templates/kubernetes-ray.yml.j2 template, why we just set cpu/memory for resource requests, but leave it empty for limits?
If we have LimitRange configured in the namespace, the default limits maybe smaller that the skypilot configured requests, and will make the pod creation failed. I think we should use the same value for the limits to make it work better.

**Comment by nkwangleiGIT** [comment]
submit a PR for this: https://github.com/skypilot-org/skypilot/pull/4357

**Comment by romilbhardwaj** [comment]
Hi @nkwangleiGIT - we do not set limits because we want SkyPilot pods to use any idle CPU cycles instead of being throttled to a specific limit. https://home.robusta.dev/blog/stop-using-cpu-limits
