### ISSUE TITLE
[Core] NoCloudAccessError check is escaped from storage sync

### ISSUE THREAD

**Issue by HysunHe** [skypilot-org/skypilot#4367]
When no cloud storage enabled, a bunch of very detail exception trace shown as below, which is caused by missing the catch of NoCloudAccessError.

Each replica will use the following resources (estimated):
Considered resources (1 node):
CLOUD INSTANCE vCPUs Mem(GB) ACCELERATORS REGION/ZONE COST ($) CHOSEN
OCI VM.Standard.E4.Flex$_2_8 2 8 - af-johannesburg-1 0.04 ✔
Launching a new service 'http-server'. Proceed? [Y/n]:
⚙︎ Translating workdir to SkyPilot Storage...
Workdir: 'examples/serve/http_server' -> storage: 'skypilot-workdir-hysunhe-eff32b4c'.
Traceback (most recent call last):
File "/home/hysunhe/miniconda3/envs/sky/bin/sky", line 8, in
sys.exit(cli())
File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/utils/common_utils.py", line 366, in _record
return f(*args, **kwargs)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/cli.py", line 831, in invoke
return super().invoke(ctx)
File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/utils/common_utils.py", line 366, in _record
return f(*args, **kwargs)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/cli.py", line 831, in invoke
return super().invoke(ctx)
File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/hysunhe/miniconda3/envs/sky/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/utils/common_utils.py", line 386, in _record
return f(*args, **kwargs)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/utils/common_utils.py", line 386, in _record
return f(*args, **kwargs)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/cli.py", line 4181, in serve_up
serve_lib.up(task, service_name)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/utils/common_utils.py", line 386, in _record
return f(*args, **kwargs)
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/serve/core.py", line 136, in up
controller_utils.maybe_translate_local_file_mounts_and_sync_up(
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/utils/controller_utils.py", line 820, in maybe_translate_local_file_mounts_and_sync_up
task.sync_storage_mounts()
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/task.py", line 960, in sync_storage_mounts
store_type, store_region = self._get_preferred_store()
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/task.py", line 925, in _get_preferred_store
storage_lib.get_cached_enabled_storage_clouds_or_refresh(
File "/home/hysunhe/prjdev/skypilot/skypilot_oci/sky/data/storage.py", line 90, in get_cached_enabled_storage_clouds_or_refresh
raise exceptions.NoCloudAccessError(
sky.exceptions.NoCloudAccessError: No cloud access available for storage. Please check your cloud credentials.
(sky) hysunhe@HYHE-PF1ZGYCQ:~/prjdev/skypilot/skypilot_oci$

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by HysunHe** [comment]
Fixed by PR: https://github.com/skypilot-org/skypilot/pull/4366
