### ISSUE TITLE
[Core] Autostop/autodown fails on AWS

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4412]
Getting the following logs for autostopping a cluster on AWS, in `~/.sky/skylet.log`
```
AutostopEvent error: module 'urllib3.util' has no attribute 'PROTOCOL_TLS'
Traceback (most recent call last):
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/skylet/events.py", line 51, in run
    self._run()
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/skylet/events.py", line 135, in _run
    self._stop_cluster(autostop_config)
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/skylet/events.py", line 153, in _stop_cluster
    self._stop_cluster_with_new_provisioner(autostop_config, config,
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/skylet/events.py", line 259, in _stop_cluster_with_new_provisioner
    operation_fn(provider_name=provider_name,
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/__init__.py", line 52, in _wrapper
    return impl(*args, **kwargs)
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/aws/instance.py", line 617, in stop_instances
    ec2 = _default_ec2_resource(region)
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/aws/instance.py", line 96, in _default_ec2_resource
    return aws.resource('ec2',
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/adaptors/aws.py", line 149, in resource
    config = botocore_config().Config(
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/adaptors/common.py", line 64, in wrapper
    m.load_module()
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/adaptors/common.py", line 31, in load_module
    self._module = importlib.import_module(self._module_name)
  File "/home/ubuntu/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import (
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/docs/client.py", line 18, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/utils.py", line 39, in <module>
    import botocore.httpsession
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/botocore/httpsession.py", line 45, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 97, in <module>
    util.PROTOCOL_TLS: OpenSSL.SSL.SSLv23_METHOD,
AttributeError: module 'urllib3.util' has no attribute 'PROTOCOL_TLS'
```

It is likely because the latest `botocore` library does not support `urllib3<2`

https://github.com/skypilot-org/skypilot/blob/10c5f21a619a6c4f8d89f788824627888008195a/setup.py#L195-L210

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by Michaelvll** [comment]
Hmm, this may be an unrelated issue due to manual update. Replacing the label to triage.
