### ISSUE TITLE
Run with UV package manager

### ISSUE THREAD

**Issue by kevinsimper** [skypilot-org/skypilot#4428]
Love skypilot 💝

I was trying to use with UV, but it fails on this command

I guess skypilot is meant to be run within a managed venv, so I get why it fails, but it would be nice if skypilot had uv support.

```
$ uv run sky launch -c gatx skypilot.yaml
Task from YAML spec: skypilot.yaml
Considered resources (1 node):
---------------------------------------------------------------------------------------------
 CLOUD   INSTANCE       vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN
---------------------------------------------------------------------------------------------
 GCP     n1-highmem-4   4       26        T4:1           us-central1-a   0.59          ✔
---------------------------------------------------------------------------------------------
Launching a new cluster 'gatx'. Proceed? [Y/n]: y

Traceback (most recent call last):
  File "/Users/xx/.venv/lib/python3.12/site-packages/sky/backends/wheel_utils.py", line 103, in _build_sky_wheel
    subprocess.run([
  File "/Users/xx/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pip3', 'wheel', '--no-deps', '/var/folders/zy/fgmdfk0123304wg6ck35mcvm0000gn/T/tmpvsinlzlv/', '--wheel-dir', '/var/folders/zy/fgmdfk0123304wg6ck35mcvm0000gn/T/tmpvsinlzlv']' returned non-zero exit status 1.
```

_Version & Commit info:_
* `sky -v`: skypilot, version 0.7.0
* `sky -c`: skypilot, commit 3f625886bf1b13ee463a9f8e0f6741f620f7f66f

**Comment by concretevitamin** [comment]
Thanks for the report @kevinsimper 🙌  cc @cg505 who's been looking into using uv in the backend.

**Comment by cg505** [comment]
Hi @kevinsimper! How did you install skypilot? Does `uv pip install pip` resolve this issue?

**Comment by cg505** [comment]
I think we should add `pip` as a package dependency to resolve this, since we use it during wheel build. At the moment we are just assuming it's present, but this won't be the case in `uv` venvs. @Michaelvll any concern with this?

**Comment by kesitrifork** [comment]
@cg505 No, you install with `uv add skypilot[gcp]`

The bigger problem is that uv is not a pip replacement (their words)

So running subcommand to run a pip command will execute the wrong pip executable, and wheel is not a happy command to support because of legacy reasons https://github.com/astral-sh/uv/issues/1681

**Comment by cg505** [comment]
@kevinsimper In my testing, `uv add pip` (or `uv pip install pip` if you are just using a venv, outside a project) seems to work. It looks like `uv` will set up the environment correctly so that we get the right pip executable. (Specifically, it modifies PATH so that the venv bin is the very first element, and sets the VIRTUAL_ENV var as well.)
Ideally this can happen without using a subprocess, but it seems like it works either way.

**Comment by cg505** [comment]
To clarify, I'm NOT asking you to install pip _so that you can use it to install skypilot instead of uv_ - just asking you to install it so that skypilot can use it correctly during provisioning.

**Comment by kevinsimper** [comment]
@cg505 It does work and I have been using it for the past week without any problems on both a M4 and a Ubuntu machine 👍 Thanks for the suggestion!

**Comment by cg505** [comment]
Thanks for the confirmation! I'll look into adding this as an explicit dependency on the package so that this extra step is not necessary.

**Comment by Michaelvll** [comment]
This is actually fixed in #6880

**Comment by cg505** [comment]
@Michaelvll That PR is not merged. Is there another one you meant?

**Comment by Michaelvll** [comment]
Oops sorry, I mean #6893
