### ISSUE TITLE
[bug] Task name is required when running `sky launch --docker`

### ISSUE THREAD

**Issue by gaocegege** [skypilot-org/skypilot#4506]
The documentation at https://docs.skypilot.co/en/latest/reference/yaml-spec.html#task-yaml states that the task name is optional; however, using the localdocker backend will result in an error if it is not specified.

```yaml
# Task name (optional), used for display purposes.
# name: my-task

resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: kubernetes

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  conda env list
```

```
(sky) ➜  hello-sky git:(f0ebf13b) ✗ sky launch ./hello-world.yaml --docker
Task from YAML spec: ./hello-world.yaml
Considered resources (1 node):
---------------------------------------------------------------------------------------------
 CLOUD        INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
---------------------------------------------------------------------------------------------
 Kubernetes   2CPU--2GB   2       2         -              xxxxxxx     0.00          ✔
---------------------------------------------------------------------------------------------
Launching a new cluster 'sky-4242-gcgg'. Proceed? [Y/n]: y

Traceback (most recent call last):
  File "/home/gcgg/applications/miniconda3/bin/sky", line 33, in <module>
    sys.exit(load_entry_point('skypilot', 'console_scripts', 'sky')())
  File "/home/gcgg/applications/miniconda3/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/gcgg/applications/miniconda3/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/gcgg/code/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/cli.py", line 838, in invoke
    return super().invoke(ctx)
  File "/home/gcgg/applications/miniconda3/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gcgg/applications/miniconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gcgg/applications/miniconda3/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/cli.py", line 1159, in launch
    _launch_with_confirm(task,
  File "/home/gcgg/code/skypilot/sky/cli.py", line 628, in _launch_with_confirm
    sky.launch(
  File "/home/gcgg/code/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/execution.py", line 529, in launch
    return _execute(
  File "/home/gcgg/code/skypilot/sky/execution.py", line 302, in _execute
    handle = backend.provision(
  File "/home/gcgg/code/skypilot/sky/utils/common_utils.py", line 386, in _record
    return f(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/utils/common_utils.py", line 366, in _record
    return f(*args, **kwargs)
  File "/home/gcgg/code/skypilot/sky/backends/backend.py", line 84, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
  File "/home/gcgg/code/skypilot/sky/backends/local_docker_backend.py", line 149, in _provision
    assert task.name is not None, ('Task name cannot be None - have you '
AssertionError: Task name cannot be None - have you specified a task name?
```

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by romilbhardwaj** [comment]
Hey @gaocegege  - `LocalDockerBackend` has been deprecated and is replaced by our [Kubernetes support](https://docs.skypilot.co/en/latest/reference/kubernetes/index.html). Recommended way to to run locally is to use a [local Kubernetes cluster](https://docs.skypilot.co/en/latest/reference/kubernetes/kubernetes-deployment.html#kubernetes-setup-kind) (`sky local up`). 

Moving discussion on the deprecation to https://github.com/skypilot-org/skypilot/issues/4508#issuecomment-2561949838.

**Comment by gaocegege** [comment]
Then maybe we should mark it deprecated in docs.
