### ISSUE TITLE
Fail to launch GCP instance when the account does not have IAM permission

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#964]
A GCP user with no IAM setting permission (the permission in the following figure) will not be able to get setIAMPolicy for the ray-autoscaler service IAM and cause the following error. 
![image](https://user-images.githubusercontent.com/6753189/178210589-fcb20664-1f11-4435-a472-e8d8bccbe796.png)

```
I 07-10 16:30:56 cloud_vm_ray_backend.py:994] Launching on GCP us-west1 (us-west1-b)
I 07-10 16:31:11 cloud_vm_ray_backend.py:496] Got googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/prod-635e:setIamPolicy?alt=json returned "Policy update access denied.". Details: "Policy update access denied.">
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] Failed to terminate sky-rachel-test. If you want to ignore this error and remove the cluster from from Sky's status table, use `sky down --purge`.
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] **** STDOUT ****
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] 2022-07-10 16:31:15,413	INFO commands.py:348 -- Checking External environment settings
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] 
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] **** STDERR ****
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] 2022-07-10 16:31:14,079	INFO util.py:335 -- setting max workers for head node type to 0
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] Traceback (most recent call last):
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/bin/ray", line 8, in <module>
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     sys.exit(main())
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2339, in main
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return cli()
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return self.main(*args, **kwargs)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/click/core.py", line 1053, in main
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     rv = self.invoke(ctx)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return _process_result(sub_ctx.command.invoke(sub_ctx))
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return ctx.invoke(self.callback, **ctx.params)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/click/core.py", line 754, in invoke
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return __callback(*args, **kwargs)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return f(*args, **kwargs)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/ray/scripts/scripts.py", line 1223, in down
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     teardown_cluster(
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 401, in teardown_cluster
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     config = _bootstrap_config(config)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 376, in _bootstrap_config
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     resolved_config = provider_cls.bootstrap_config(config)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/sky/skylet/providers/gcp/node_provider.py", line 238, in bootstrap_config
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return bootstrap_gcp(cluster_config)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/sky/skylet/providers/gcp/config.py", line 268, in bootstrap_gcp
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     config = _configure_iam_role(config, crm, iam)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/sky/skylet/providers/gcp/config.py", line 338, in _configure_iam_role
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     _add_iam_policy_binding(service_account, roles, crm)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/sky/skylet/providers/gcp/config.py", line 610, in _add_iam_policy_binding
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     result = crm.projects().setIamPolicy(
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     return wrapped(*args, **kwargs)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]   File "/Users/qiuruizeng/Desktop/UCSD/anaconda3/envs/sky/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011]     raise HttpError(resp, content, uri=self.uri)
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/prod-635e:setIamPolicy?alt=json returned "Policy update access denied.". Details: "Policy update access denied.">
E 07-10 16:31:25 cloud_vm_ray_backend.py:2011] 
W 07-10 16:31:25 cloud_vm_ray_backend.py:1123] Failed to acquire resources in all regions/zones of GCP. Try changing resource requirements or use another cloud.
W 07-10 16:31:25 cloud_vm_ray_backend.py:1125] 
W 07-10 16:31:25 cloud_vm_ray_backend.py:1125] Provision failed for 1x GCP(n1-highmem-8). Trying other launchable resources (if any).
No existing clusters.
```

This will cause new users with limited permission from an organization fail to run sky for GCP. It seems the service IAM account may not be necessary as long as the user have the access to the compute engine. We may be able to modify our own copy of the `node_provider` in skylet to make it work.

**Comment by Michaelvll** [comment]
This has been fixed by our minimal permission list for GCP in our doc.
